import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem('language');
    return savedLanguage || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  // Traductions complètes
  const translations = {
    fr: {
      // Navigation
      dashboard: 'Tableau de Bord',
      team: 'Équipe',
      demands: 'Demandes RH',
      payslip: 'Fiche de Paie',
      archives: 'Archives',
      statistics: 'Statistiques',
      settings: 'Paramètres',
      visa: 'Demandes Visa',
      logout: 'Déconnexion',
      language: 'Langue',
      
      // Header et titres
      appTitle: 'RH Manager',
      appSubtitle: 'Gestion des ressources humaines',
      lastUpdate: 'Dernière mise à jour',
      welcome: 'Bienvenue',
      overview: 'Vue d\'ensemble',
      details: 'Détails',
      actions: 'Actions',
      quickActions: 'Actions Rapides',
      summary: 'Résumé',
      
      // Dashboard
      totalEmployees: 'Effectif Total',
      newThisMonth: 'Nouveaux ce mois',
      contractsToRenew: 'Contrats à renouveler',
      totalSalary: 'Masse Salariale',
      archivesCount: 'Employés Archivés',
      manageTeam: 'Gérer l\'Équipe',
      viewStatistics: 'Voir les statistiques',
      viewArchives: 'Consulter les archives',
      exportData: 'Exporter les Données',
      activeGrowth: 'Croissance active',
      stableThisMonth: 'Stable ce mois-ci',
      next30Days: 'Dans les 30 prochains jours',
      monthlyGross: 'Salaire brut mensuel total',
      formerEmployees: 'Anciens employés',
      
      // Team
      employeeManagement: 'Gestion de l\'Équipe',
      consultEmployees: 'Consulter et gérez les informations de vos employés actifs',
      searchPlaceholder: 'Rechercher par nom, prénom, poste ou matricule...',
      employeesFound: 'employé(s) trouvé(s)',
      refresh: 'Actualiser',
      addEmployee: 'Ajouter Employé',
      noResults: 'Aucun employé trouvé',
      addFirstEmployee: 'Ajouter le premier employé',
      
      // Employee Modal
      employeeDetails: 'Détails de l\'Employé',
      personalInfo: 'Informations Personnelles',
      professionalInfo: 'Informations Professionnelles',
      emailContacts: 'Coordonnées Email',
      documents: 'Documents',
      editInfo: 'Modifier les informations',
      save: 'Sauvegarder',
      cancel: 'Annuler',
      changePhoto: 'Changer la photo',
      departureDate: 'Date de départ',
      archiveEmployee: 'Archiver l\'employé',
      archiveHint: 'Ajouter une date de départ pour pouvoir archiver l\'employé',
      addUpdateDossier: 'Ajouter/Mettre à jour le dossier RH',
      noDocument: 'Aucun document',
      requiredField: 'Ce champ est requis',
      optional: 'Optionnel',
      
      // Add Employee Modal
      addNewEmployee: 'Ajouter un Nouvel Employé',
      employeePhoto: 'Photo de l\'employé',
      clickToSelectPhoto: 'Cliquez pour sélectionner une photo',
      photoRequirements: 'JPG, PNG, GIF (max 5MB)',
      choosePhoto: 'Choisir une photo',
      removePhoto: 'Supprimer',
      employeeEmail: 'Email employé',
      supervisor1Email: 'Email Responsable 1',
      supervisor2Email: 'Email Responsable 2',
      idNumber: 'CIN',
      passport: 'Passeport',
      birthDate: 'Date de Naissance',
      position: 'Poste',
      department: 'Site/Département',
      contractType: 'Type de Contrat',
      startDate: 'Date Début',
      grossSalary: 'Salaire Brut',
      createEmployee: 'Créer Employé',
      uploadingPhoto: 'Upload photo...',
      creating: 'Création...',
      
      // Archive Modal
      archiveEmployeeTitle: 'Archiver l\'Employé',
      uploadDepartureInterview: 'Télécharger le PDF d\'entretien de départ',
      required: 'Obligatoire',
      attachReport: 'Joignez le rapport d\'entretien de départ au format PDF',
      clickToSelectFile: 'Cliquez pour sélectionner un fichier',
      dragDropHere: 'ou glissez-déposez votre fichier PDF ici',
      pdfOnly: 'Format PDF uniquement',
      uploading: 'Envoi en cours',
      doNotClose: 'Ne fermez pas cette fenêtre pendant l\'upload...',
      uploadSuccess: 'PDF téléchargé avec succès !',
      previewPDF: 'Aperçu du PDF',
      changeFile: 'Changer le fichier',
      confirmArchive: 'Archiver l\'employé',
      processing: 'Traitement en cours...',
      archiveNote: 'L\'archivage prendra effet immédiatement après confirmation',
      
      // Archives Page
      archivedEmployees: 'Archives des Employés',
      formerEmployeesList: 'Liste des employés ayant quitté l\'entreprise',
      withInterview: 'Avec Entretien',
      departureInterviews: 'Entretiens de départ',
      searchArchives: 'Rechercher dans les archives...',
      backToTeam: 'Retour à l\'équipe',
      noArchives: 'Aucun employé archivé',
      archivedWillAppear: 'Les employés archivés apparaîtront ici après leur départ',
      viewActiveEmployees: 'Voir les employés actifs',
      departure: 'Départ',
      viewInterview: 'Voir l\'entretien',
      archiveDetails: 'Détails de l\'Employé Archivé',
      archiveDocuments: 'Documents d\'Archive',
      mainArchiveDocument: 'Document principal d\'archive',
      legacyFormat: 'Ancien format de document',
      completeHRFile: 'Dossier RH complet',
      noDocumentsAvailable: 'Aucun document d\'archive disponible',
      archivedWithoutDocument: 'L\'employé a été archivé sans document d\'entretien de départ',
      archiveInfo: 'Informations d\'Archivage',
      lastUpdate: 'Dernière mise à jour',
      creationDate: 'Date de création',
      documentsKept: 'Les documents d\'archive sont conservés pour une durée de 5 ans minimum',
      printDetails: 'Imprimer',
      backToList: 'Retour à la liste',
      
      // Statistics
      statisticsDashboard: 'Tableau de Bord Statistiques',
      hrAnalysis: 'Analyse détaillée de vos ressources humaines',
      departmentDistribution: 'Répartition par Département',
      contractTypes: 'Types de Contrat',
      salaryAnalysis: 'Analyse des Salaires',
      recentHires: 'Dernières Embauches',
      minimumSalary: 'Salaire Minimum',
      maximumSalary: 'Salaire Maximum',
      medianSalary: 'Salaire Médian',
      averageSalary: 'Salaire Moyen',
      exportDataPDF: 'Exporter en PDF',
      exportStatisticsExcel: 'Exporter Statistiques Excel',
      exportEmployeesExcel: 'Exporter Liste Employés Excel',
      noHiresThisMonth: 'Aucune embauche ce mois-ci',
      
      // Demandes RH
      hrRequests: 'Consultation des Demandes RH',
      requestTracking: 'Visualisation et suivi des demandes des collaborateurs',
      searchFilters: 'Filtres de recherche',
      allStatus: 'Tous les statuts',
      allTypes: 'Tous les types',
      allDates: 'Toutes les dates',
      fromDate: 'À partir du',
      toDate: 'Jusqu\'au',
      activeFilters: 'Filtres actifs',
      clearFilters: 'Effacer filtres',
      exportExcel: 'Exporter Excel',
      totalRequests: 'Total demandes',
      pending: 'En attente',
      approved: 'Approuvées',
      refused: 'Refusées',
      results: 'Résultats',
      page: 'Page',
      of: 'sur',
      noRequests: 'Aucune demande trouvée',
      noMatchingCriteria: 'Aucune demande ne correspond à vos critères de recherche',
      showAllRequests: 'Afficher toutes les demandes',
      leaveType: 'Type de congé',
      approvalProcess: 'Processus d\'approbation',
      createdOn: 'Créé le',
      lastUpdated: 'Dernière mise à jour',
      refusalComment: 'Commentaire de refus',
      viewDetails: 'Voir les détails complets',
      generalInfo: 'Informations générales',
      employeeInfo: 'Informations employé',
      requestDetails: 'Détails de la demande',
      startDateReq: 'Date début',
      returnDate: 'Date retour',
      departureTime: 'Heure départ',
      returnTime: 'Heure retour',
      travelExpenses: 'Frais déplacement',
      halfDay: 'Demi-journée',
      close: 'Fermer',
      supervisor1: 'Responsable 1',
      supervisor2: 'Responsable 2',
      notAssigned: 'Non assigné',
      notRequired: 'Non applicable',
      
      // Fiche de Paie
      payslip: 'Fiche de Paie',
      autoSendPayslips: 'Envoi automatique des fiches de paie aux employés',
      importPDF: 'Importer un fichier PDF',
      pdfDescription: 'Le PDF doit contenir une fiche de paie par page. Chaque fiche doit avoir le matricule de l\'employé (MATR.).',
      choosePDF: 'Choisir un fichier PDF',
      processAndSend: 'Traiter et envoyer',
      processingInProgress: 'Traitement en cours...',
      extractingMatricules: 'Extraction des matricules et envoi des emails...',
      mayTakeSeveralMinutes: 'Cela peut prendre plusieurs minutes selon le nombre de pages',
      processingComplete: 'Traitement terminé',
      sheetsSent: 'fiche(s) envoyée(s) sur',
      pages: 'page(s)',
      errorDetails: 'Détails des erreurs',
      employeeMatricule: 'Matricule',
      employee: 'Employé',
      error: 'Erreur',
      
      // Login
      login: 'Connexion',
      loginToYourAccount: 'Connectez-vous à votre espace',
      email: 'Email',
      password: 'Mot de passe',
      forgotPassword: 'Mot de passe oublié ?',
      resetPassword: 'Réinitialiser le mot de passe',
      enterEmailForNewPassword: 'Entrez votre adresse email pour recevoir un nouveau mot de passe.',
      sendNewPassword: 'Envoyer un nouveau mot de passe',
      backToLogin: 'Retour à la connexion',
      temporaryPasswordNote: 'Un email contenant un nouveau mot de passe vous sera envoyé. Ce mot de passe est temporaire, changez-le après connexion. Vérifiez vos spams si vous ne recevez pas l\'email.',
      appDescription: 'Application de gestion des ressources humaines',
      version: 'Version',
      
      // Settings
      settings: 'Paramètres',
      managePreferences: 'Gérez vos préférences et paramètres de l\'application',
      chooseLanguage: 'Choisissez la langue d\'affichage de l\'application',
      currentLanguage: 'Langue actuelle',
      changeEffectiveImmediately: 'Le changement prend effet immédiatement sur toute l\'application',
      notifications: 'Notifications',
      configureNotifications: 'Configurez comment vous recevez les notifications',
      emailNotifications: 'Notifications par email',
      receiveAlertsByEmail: 'Recevez les alertes importantes par email',
      pushNotifications: 'Notifications push',
      realTimeAlerts: 'Alertes en temps réel dans l\'application',
      weeklyReport: 'Rapport hebdomadaire',
      weeklySummaryEmail: 'Recevez un résumé hebdomadaire par email',
      about: 'À propos',
      userGuide: 'Guide d\'utilisation',
      technicalSupport: 'Support technique',
      termsOfUse: 'Conditions d\'utilisation',
      privacyPolicy: 'Politique de confidentialité',
      saveChanges: 'Enregistrer les modifications',
      restoreDefaults: 'Restaurer les paramètres par défaut',
      
      // Common
      loading: 'Chargement...',
      yes: 'Oui',
      no: 'Non',
      na: 'N/A',
      optional: 'Optionnel',
      required: 'Obligatoire',
      success: 'Succès',
      error: 'Erreur',
      warning: 'Avertissement',
      info: 'Information',
      confirm: 'Confirmer',
      delete: 'Supprimer',
      edit: 'Modifier',
      view: 'Voir',
      download: 'Télécharger',
      upload: 'Uploader',
      search: 'Rechercher',
      filter: 'Filtrer',
      sort: 'Trier',
      previous: 'Précédent',
      next: 'Suivant',
      first: 'Premier',
      last: 'Dernier',
      today: 'Aujourd\'hui',
      yesterday: 'Hier',
      thisWeek: 'Cette semaine',
      thisMonth: 'Ce mois',
      thisYear: 'Cette année',
      all: 'Tous',
      none: 'Aucun',
      unknown: 'Inconnu',
      notAvailable: 'Non disponible',
      notSpecified: 'Non spécifié',
      add: 'Ajouter',
      remove: 'Supprimer',
      update: 'Mettre à jour',
      create: 'Créer',
      cancel: 'Annuler',
      save: 'Sauvegarder',
      close: 'Fermer',
      back: 'Retour',
      nextStep: 'Étape suivante',
      finish: 'Terminer',
      print: 'Imprimer',
      export: 'Exporter',
      import: 'Importer',
      refresh: 'Actualiser',
      reset: 'Réinitialiser',
      apply: 'Appliquer',
      select: 'Sélectionner',
      choose: 'Choisir',
      browse: 'Parcourir',
      dragAndDrop: 'Glisser-déposer',
      or: 'ou',
      and: 'et',
      with: 'avec',
      without: 'sans',
      per: 'par',
      total: 'Total',
      average: 'Moyenne',
      minimum: 'Minimum',
      maximum: 'Maximum',
      median: 'Médiane',
      count: 'Nombre',
      percentage: 'Pourcentage',
      ratio: 'Ratio',
      status: 'Statut',
      type: 'Type',
      date: 'Date',
      time: 'Heure',
      datetime: 'Date et heure',
      name: 'Nom',
      firstName: 'Prénom',
      lastName: 'Nom',
      fullName: 'Nom complet',
      emailAddress: 'Adresse email',
      phone: 'Téléphone',
      address: 'Adresse',
      city: 'Ville',
      country: 'Pays',
      postCode: 'Code postal',
      description: 'Description',
      comments: 'Commentaires',
      notes: 'Notes',
      remarks: 'Remarques',
      attachment: 'Pièce jointe',
      file: 'Fichier',
      document: 'Document',
      image: 'Image',
      photo: 'Photo',
      video: 'Vidéo',
      audio: 'Audio',
      link: 'Lien',
      url: 'URL',
      size: 'Taille',
      format: 'Format',
      extension: 'Extension',
      dimensions: 'Dimensions',
      resolution: 'Résolution',
      quality: 'Qualité',
      settings: 'Paramètres',
      preferences: 'Préférences',
      configuration: 'Configuration',
      options: 'Options',
      advanced: 'Avancé',
      basic: 'Basique',
      simple: 'Simple',
      complex: 'Complexe',
      easy: 'Facile',
      difficult: 'Difficile',
      quick: 'Rapide',
      slow: 'Lent',
      fast: 'Vite',
      new: 'Nouveau',
      old: 'Ancien',
      recent: 'Récent',
      current: 'Actuel',
      previous: 'Précédent',
      next: 'Suivant',
      future: 'Futur',
      past: 'Passé',
      present: 'Présent',
      active: 'Actif',
      inactive: 'Inactif',
      enabled: 'Activé',
      disabled: 'Désactivé',
      visible: 'Visible',
      hidden: 'Caché',
      public: 'Public',
      private: 'Privé',
      shared: 'Partagé',
      personal: 'Personnel',
      professional: 'Professionnel',
      business: 'Affaires',
      personalInfo: 'Informations personnelles',
      professionalInfo: 'Informations professionnelles',
      contactInfo: 'Coordonnées',
      financialInfo: 'Informations financières',
      legalInfo: 'Informations légales',
      medicalInfo: 'Informations médicales',
      educationalInfo: 'Informations éducatives',
      workInfo: 'Informations professionnelles',
      projectInfo: 'Informations projet',
      taskInfo: 'Informations tâche',
      meetingInfo: 'Informations réunion',
      eventInfo: 'Informations événement',
      travelInfo: 'Informations voyage',
      expenseInfo: 'Informations dépenses',
      timeOffInfo: 'Informations congés',
      performanceInfo: 'Informations performance',
      evaluationInfo: 'Informations évaluation',
      trainingInfo: 'Informations formation',
      developmentInfo: 'Informations développement',
      careerInfo: 'Informations carrière',
      salaryInfo: 'Informations salaire',
      benefitsInfo: 'Informations avantages',
      contractInfo: 'Informations contrat',
      policyInfo: 'Informations politique',
      procedureInfo: 'Informations procédure',
      guidelineInfo: 'Informations guide',
      manualInfo: 'Informations manuel',
      reportInfo: 'Informations rapport',
      analysisInfo: 'Informations analyse',
      statisticsInfo: 'Informations statistiques',
      dataInfo: 'Informations données',
      information: 'Informations',
      knowledge: 'Connaissance',
      wisdom: 'Sagesse',
      insight: 'Perspective',
      perspective: 'Point de vue',
      viewPoint: 'Point de vue',
      opinion: 'Avis',
      suggestion: 'Suggestion',
      recommendation: 'Recommandation',
      advice: 'Conseil',
      tip: 'Astuce',
      trick: 'Astuce',
      hint: 'Indice',
      clue: 'Indice',
      evidence: 'Preuve',
      proof: 'Preuve',
      verification: 'Vérification',
      validation: 'Validation',
      confirmation: 'Confirmation',
      approval: 'Approbation',
      authorization: 'Autorisation',
      permission: 'Permission',
      consent: 'Consentement',
      agreement: 'Accord',
      contract: 'Contrat',
      deal: 'Accord',
      arrangement: 'Arrangement',
      plan: 'Plan',
      schedule: 'Calendrier',
      timeline: 'Calendrier',
      deadline: 'Échéance',
      milestone: 'Jalon',
      goal: 'Objectif',
      objective: 'Objectif',
      target: 'Cible',
      aim: 'But',
      purpose: 'But',
      mission: 'Mission',
      vision: 'Vision',
      value: 'Valeur',
      principle: 'Principe',
      belief: 'Croyance',
      attitude: 'Attitude',
      behavior: 'Comportement',
      action: 'Action',
      reaction: 'Réaction',
      response: 'Réponse',
      feedback: 'Retour',
      review: 'Revue',
      assessment: 'Évaluation',
      evaluation: 'Évaluation',
      appraisal: 'Évaluation',
      rating: 'Note',
      score: 'Score',
      grade: 'Note',
      mark: 'Marque',
      result: 'Résultat',
      outcome: 'Résultat',
      output: 'Sortie',
      product: 'Produit',
      service: 'Service',
      solution: 'Solution',
      answer: 'Réponse',
      question: 'Question',
      problem: 'Problème',
      issue: 'Problème',
      challenge: 'Défi',
      difficulty: 'Difficulté',
      obstacle: 'Obstacle',
      barrier: 'Barrière',
      constraint: 'Contrainte',
      limitation: 'Limitation',
      restriction: 'Restriction',
      condition: 'Condition',
      requirement: 'Exigence',
      specification: 'Spécification',
      standard: 'Standard',
      criteria: 'Critère',
      measure: 'Mesure',
      metric: 'Métrique',
      indicator: 'Indicateur',
      signal: 'Signal',
      alert: 'Alerte',
      warning: 'Avertissement',
      danger: 'Danger',
      risk: 'Risque',
      threat: 'Menace',
      opportunity: 'Opportunité',
      advantage: 'Avantage',
      benefit: 'Avantage',
      gain: 'Gain',
      profit: 'Profit',
      loss: 'Perte',
      cost: 'Coût',
      price: 'Prix',
      valueMoney: 'Valeur',
      amount: 'Montant',
      quantity: 'Quantité',
      number: 'Nombre',
      countNumber: 'Nombre',
      totalNumber: 'Total',
      sum: 'Somme',
      averageNumber: 'Moyenne',
      medianNumber: 'Médiane',
      minimumNumber: 'Minimum',
      maximumNumber: 'Maximum',
      range: 'Plage',
      interval: 'Intervalle',
      period: 'Période',
      duration: 'Durée',
      frequency: 'Fréquence',
      rate: 'Taux',
      ratioNumber: 'Ratio',
      percentageNumber: 'Pourcentage',
      proportion: 'Proportion',
      fraction: 'Fraction',
      decimal: 'Décimal',
      integer: 'Entier',
      whole: 'Entier',
      part: 'Partie',
      section: 'Section',
      segment: 'Segment',
      portion: 'Portion',
      piece: 'Morceau',
      bit: 'Bit',
      byte: 'Byte',
      kilobyte: 'Kilooctet',
      megabyte: 'Mégaoctet',
      gigabyte: 'Gigaoctet',
      terabyte: 'Téraoctet',
      petabyte: 'Pétaoctet',
      exabyte: 'Exaoctet',
      zettabyte: 'Zettaoctet',
      yottabyte: 'Yottaoctet',
      second: 'Seconde',
      minute: 'Minute',
      hour: 'Heure',
      day: 'Jour',
      week: 'Semaine',
      month: 'Mois',
      year: 'Année',
      decade: 'Décennie',
      century: 'Siècle',
      millennium: 'Millénaire',
      era: 'Ère',
      age: 'Âge',
      periodTime: 'Période',
      epoch: 'Époque',
      dateTime: 'Date et heure',
      timestamp: 'Horodatage',
      timezone: 'Fuseau horaire',
      calendar: 'Calendrier',
      scheduleTime: 'Calendrier',
      appointment: 'Rendez-vous',
      meeting: 'Réunion',
      event: 'Événement',
      occasion: 'Occasion',
      celebration: 'Célébration',
      festival: 'Festival',
      holiday: 'Vacances',
      vacation: 'Vacances',
      leave: 'Congé',
      break: 'Pause',
      rest: 'Repos',
      sleep: 'Sommeil',
      wake: 'Réveil',
      morning: 'Matin',
      afternoon: 'Après-midi',
      evening: 'Soir',
      night: 'Nuit',
      midnight: 'Minuit',
      noon: 'Midi',
      dawn: 'Aube',
      dusk: 'Crépuscule',
      sunrise: 'Lever du soleil',
      sunset: 'Coucher du soleil',
      daybreak: 'Point du jour',
      twilight: 'Crépuscule',
      darkness: 'Obscurité',
      light: 'Lumière',
      dark: 'Sombre',
      bright: 'Brillant',
      dim: 'Faible',
      clear: 'Clair',
      cloudy: 'Nuageux',
      rainy: 'Pluvieux',
      snowy: 'Neigeux',
      windy: 'Venteux',
      stormy: 'Orageux',
      sunny: 'Ensoleillé',
      hot: 'Chaud',
      cold: 'Froid',
      warm: 'Chaud',
      cool: 'Frais',
      freezing: 'Gelé',
      boiling: 'Bouillant',
      temperature: 'Température',
      weather: 'Temps',
      climate: 'Climat',
      season: 'Saison',
      spring: 'Printemps',
      summer: 'Été',
      autumn: 'Automne',
      winter: 'Hiver',
      north: 'Nord',
      south: 'Sud',
      east: 'Est',
      west: 'Ouest',
      direction: 'Direction',
      location: 'Emplacement',
      position: 'Position',
      place: 'Lieu',
      site: 'Site',
      venue: 'Lieu',
      addressLocation: 'Adresse',
      street: 'Rue',
      avenue: 'Avenue',
      boulevard: 'Boulevard',
      road: 'Route',
      highway: 'Autoroute',
      freeway: 'Autoroute',
      expressway: 'Voie express',
      streetAddress: 'Adresse postale',
      postalAddress: 'Adresse postale',
      mailingAddress: 'Adresse postale',
      physicalAddress: 'Adresse physique',
      digitalAddress: 'Adresse numérique',
      ipAddress: 'Adresse IP',
      urlAddress: 'URL',
      webAddress: 'Adresse web',
      emailAddressFull: 'Adresse email',
      phoneNumber: 'Numéro de téléphone',
      mobileNumber: 'Numéro de mobile',
      landline: 'Ligne fixe',
      fax: 'Fax',
      pager: 'Téléavertisseur',
      voicemail: 'Messagerie vocale',
      answeringMachine: 'Répondeur',
      callForwarding: 'Renvoi d\'appel',
      conferenceCall: 'Conférence téléphonique',
      videoCall: 'Appel vidéo',
      voiceCall: 'Appel vocal',
      message: 'Message',
      textMessage: 'Message texte',
      multimediaMessage: 'Message multimédia',
      emailMessage: 'Email',
      letter: 'Lettre',
      note: 'Note',
      memo: 'Note',
      report: 'Rapport',
      documentFile: 'Document',
      fileDocument: 'Fichier',
      folder: 'Dossier',
      directory: 'Répertoire',
      archive: 'Archive',
      backup: 'Sauvegarde',
      copy: 'Copie',
      duplicate: 'Dupliquer',
      original: 'Original',
      versionFile: 'Version',
      revision: 'Révision',
      edition: 'Édition',
      issueDocument: 'Numéro',
      volume: 'Volume',
      chapter: 'Chapitre',
      sectionDocument: 'Section',
      paragraph: 'Paragraphe',
      sentence: 'Phrase',
      word: 'Mot',
      character: 'Caractère',
      letterCharacter: 'Lettre',
      numberCharacter: 'Chiffre',
      symbol: 'Symbole',
      punctuation: 'Ponctuation',
      space: 'Espace',
      tab: 'Tabulation',
      line: 'Ligne',
      pageDoc: 'Page',
      sheet: 'Feuille',
      slide: 'Diapositive',
      card: 'Carte',
      ticket: 'Ticket',
      coupon: 'Coupon',
      voucher: 'Bon',
      certificate: 'Certificat',
      diploma: 'Diplôme',
      degree: 'Diplôme',
      award: 'Prix',
      prize: 'Prix',
      trophy: 'Trophée',
      medal: 'Médaille',
      ribbon: 'Ruban',
      badge: 'Badge',
      label: 'Étiquette',
      tag: 'Étiquette',
      sticker: 'Autocollant',
      stamp: 'Timbre',
      seal: 'Sceau',
      signature: 'Signature',
      initials: 'Initiales',
      autograph: 'Autographe',
      markSignature: 'Marque',
      brand: 'Marque',
      trademark: 'Marque déposée',
      logo: 'Logo',
      icon: 'Icône',
      imageGraphic: 'Image',
      picture: 'Image',
      photoImage: 'Photo',
      illustration: 'Illustration',
      drawing: 'Dessin',
      painting: 'Peinture',
      sketch: 'Croquis',
      diagram: 'Diagramme',
      chart: 'Graphique',
      graph: 'Graphique',
      map: 'Carte',
      planDrawing: 'Plan',
      blueprint: 'Plan',
      layout: 'Mise en page',
      design: 'Design',
      model: 'Modèle',
      prototype: 'Prototype',
      sample: 'Échantillon',
      example: 'Exemple',
      instance: 'Instance',
      case: 'Cas',
      scenario: 'Scénario',
      situation: 'Situation',
      circumstance: 'Circonstance',
      context: 'Contexte',
      environment: 'Environnement',
      setting: 'Paramètre',
      background: 'Contexte',
      foreground: 'Premier plan',
      middleGround: 'Plan moyen',
      perspectiveVisual: 'Perspective',
      viewVisual: 'Vue',
      scene: 'Scène',
      stage: 'Scène',
      theater: 'Théâtre',
      cinema: 'Cinéma',
      movie: 'Film',
      film: 'Film',
      videoMedia: 'Vidéo',
      audioMedia: 'Audio',
      music: 'Musique',
      sound: 'Son',
      noise: 'Bruit',
      silence: 'Silence',
      voice: 'Voix',
      speech: 'Discours',
      talk: 'Parler',
      conversation: 'Conversation',
      discussion: 'Discussion',
      debate: 'Débat',
      argument: 'Argument',
      dispute: 'Litige',
      conflict: 'Conflit',
      fight: 'Combat',
      battle: 'Bataille',
      war: 'Guerre',
      peace: 'Paix',
      truce: 'Trêve',
      ceasefire: 'Cessez-le-feu',
      agreementPeace: 'Accord',
      treaty: 'Traité',
      pact: 'Pacte',
      alliance: 'Alliance',
      partnership: 'Partenariat',
      collaboration: 'Collaboration',
      cooperation: 'Coopération',
      teamwork: 'Travail d\'équipe',
      group: 'Groupe',
      team: 'Équipe',
      crew: 'Équipage',
      squad: 'Équipe',
      unit: 'Unité',
      departmentOrg: 'Département',
      division: 'Division',
      branch: 'Branche',
      sectionOrg: 'Section',
      office: 'Bureau',
      headquarters: 'Siège',
      mainOffice: 'Bureau principal',
      regionalOffice: 'Bureau régional',
      localOffice: 'Bureau local',
      remoteOffice: 'Bureau distant',
      homeOffice: 'Bureau à domicile',
      virtualOffice: 'Bureau virtuel',
      coworkingSpace: 'Espace de coworking',
      workspace: 'Espace de travail',
      workstation: 'Poste de travail',
      desk: 'Bureau',
      chair: 'Chaise',
      table: 'Table',
      shelf: 'Étagère',
      cabinet: 'Armoire',
      locker: 'Casier',
      closet: 'Placard',
      room: 'Pièce',
      hall: 'Hall',
      corridor: 'Couloir',
      staircase: 'Escalier',
      elevator: 'Ascenseur',
      escalator: 'Escalier mécanique',
      entrance: 'Entrée',
      exit: 'Sortie',
      door: 'Porte',
      window: 'Fenêtre',
      wall: 'Mur',
      floor: 'Plancher',
      ceiling: 'Plafond',
      roof: 'Toit',
      foundation: 'Fondation',
      structure: 'Structure',
      building: 'Bâtiment',
      house: 'Maison',
      apartment: 'Appartement',
      condo: 'Condominium',
      townhouse: 'Maison de ville',
      villa: 'Villa',
      mansion: 'Manoir',
      palace: 'Palais',
      castle: 'Château',
      fort: 'Fort',
      tower: 'Tour',
      bridge: 'Pont',
      tunnel: 'Tunnel',
      roadInfra: 'Route',
      highwayInfra: 'Autoroute',
      freewayInfra: 'Autoroute',
      streetInfra: 'Rue',
      avenueInfra: 'Avenue',
      boulevardInfra: 'Boulevard',
      lane: 'Ruelle',
      alley: 'Allée',
      path: 'Chemin',
      trail: 'Sentier',
      walkway: 'Passerelle',
      sidewalk: 'Trottoir',
      pavement: 'Trottoir',
      roadSurface: 'Chaussée',
      asphalt: 'Asphalte',
      concrete: 'Béton',
      gravel: 'Gravier',
      dirt: 'Terre',
      grass: 'Herbe',
      soil: 'Sol',
      sand: 'Sable',
      rock: 'Roche',
      stone: 'Pierre',
      boulder: 'Rocher',
      mountain: 'Montagne',
      hill: 'Colline',
      valley: 'Vallée',
      plain: 'Plaine',
      plateau: 'Plateau',
      cliff: 'Falaise',
      canyon: 'Canyon',
      cave: 'Grotte',
      cavern: 'Caverne',
      hole: 'Trou',
      pit: 'Fosse',
      ditch: 'Fossé',
      trench: 'Tranchée',
      moat: 'Douves',
      canal: 'Canal',
      channel: 'Canal',
      river: 'Rivière',
      stream: 'Ruisseau',
      creek: 'Ruisseau',
      brook: 'Ruisseau',
      waterfall: 'Cascade',
      lake: 'Lac',
      pond: 'Étang',
      pool: 'Bassin',
      ocean: 'Océan',
      sea: 'Mer',
      bay: 'Baie',
      gulf: 'Golfe',
      strait: 'Détroit',
      channelWater: 'Canal',
      inlet: 'Crique',
      outlet: 'Sortie',
      port: 'Port',
      harbor: 'Port',
      dock: 'Quai',
      pier: 'Jetée',
      wharf: 'Quai',
      marina: 'Marina',
      beach: 'Plage',
      shore: 'Rivage',
      coast: 'Côte',
      coastline: 'Littoral',
      island: 'Île',
      peninsula: 'Péninsule',
      isthmus: 'Isthme',
      continent: 'Continent',
      countryGeo: 'Pays',
      nation: 'Nation',
      state: 'État',
      province: 'Province',
      region: 'Région',
      district: 'District',
      county: 'Comté',
      cityGeo: 'Ville',
      town: 'Ville',
      village: 'Village',
      hamlet: 'Hameau',
      metropolis: 'Métropole',
      megalopolis: 'Mégalopole',
      capital: 'Capitale',
      downtown: 'Centre-ville',
      uptown: 'Quartier résidentiel',
      suburb: 'Banlieue',
      outskirts: 'Périphérie',
      countryside: 'Campagne',
      rural: 'Rural',
      urban: 'Urbain',
      metropolitan: 'Métropolitain',
      cosmopolitan: 'Cosmopolite',
      global: 'Global',
      international: 'International',
      national: 'National',
      local: 'Local',
      regional: 'Régional',
      domestic: 'Domestique',
      foreign: 'Étranger',
      overseas: 'Outre-mer',
      abroad: 'À l\'étranger',
      home: 'Maison',
      abroadForeign: 'Étranger',
      exile: 'Exil',
      migration: 'Migration',
      immigration: 'Immigration',
      emigration: 'Émigration',
      travel: 'Voyage',
      trip: 'Voyage',
      journey: 'Voyage',
      voyage: 'Voyage',
      expedition: 'Expédition',
      adventure: 'Aventure',
      exploration: 'Exploration',
      discovery: 'Découverte',
      invention: 'Invention',
      innovation: 'Innovation',
      creation: 'Création',
      production: 'Production',
      manufacturing: 'Fabrication',
      construction: 'Construction',
      buildingProcess: 'Construction',
      assembly: 'Assemblage',
      installation: 'Installation',
      setup: 'Configuration',
      configurationProcess: 'Configuration',
      customization: 'Personnalisation',
      modification: 'Modification',
      alteration: 'Modification',
      changeProcess: 'Changement',
      transformation: 'Transformation',
      transition: 'Transition',
      evolution: 'Évolution',
      revolution: 'Révolution',
      progress: 'Progrès',
      advancement: 'Avancement',
      development: 'Développement',
      growth: 'Croissance',
      expansion: 'Expansion',
      extension: 'Extension',
      enlargement: 'Agrandissement',
      reduction: 'Réduction',
      decrease: 'Diminution',
      increase: 'Augmentation',
      rise: 'Hausse',
      fall: 'Baisse',
      drop: 'Chute',
      plunge: 'Plongeon',
      surge: 'Montée',
      spike: 'Pic',
      peak: 'Pic',
      valleyEcon: 'Vallée',
      bottom: 'Fond',
      top: 'Sommet',
      summit: 'Sommet',
      climax: 'Climax',
      culmination: 'Culmination',
      apex: 'Sommet',
      zenith: 'Zénith',
      nadir: 'Nadir',
      depth: 'Profondeur',
      height: 'Hauteur',
      width: 'Largeur',
      length: 'Longueur',
      sizePhysical: 'Taille',
      dimension: 'Dimension',
      measurement: 'Mesure',
      weight: 'Poids',
      mass: 'Masse',
      volumePhys: 'Volume',
      density: 'Densité',
      pressure: 'Pression',
      temperaturePhys: 'Température',
      heat: 'Chaleur',
      coldPhys: 'Froid',
      warmPhys: 'Chaud',
      coolPhys: 'Frais',
      freezingPhys: 'Gel',
      boilingPhys: 'Ébullition',
      melting: 'Fusion',
      freezingPoint: 'Point de congélation',
      boilingPoint: 'Point d\'ébullition',
      meltingPoint: 'Point de fusion',
      stateMatter: 'État de la matière',
      solid: 'Solide',
      liquid: 'Liquide',
      gas: 'Gaz',
      plasma: 'Plasma',
      matter: 'Matière',
      substance: 'Substance',
      material: 'Matériau',
      element: 'Élément',
      compound: 'Composé',
      mixture: 'Mélange',
      solutionChem: 'Solution',
      solvent: 'Solvant',
      solute: 'Soluté',
      concentration: 'Concentration',
      dilution: 'Dilution',
      reactionChem: 'Réaction',
      catalyst: 'Catalyseur',
      enzyme: 'Enzyme',
      protein: 'Protéine',
      aminoAcid: 'Acide aminé',
      nucleicAcid: 'Acide nucléique',
      dna: 'ADN',
      rna: 'ARN',
      gene: 'Gène',
      chromosome: 'Chromosome',
      cell: 'Cellule',
      tissue: 'Tissu',
      organ: 'Organe',
      systemBio: 'Système',
      organism: 'Organisme',
      species: 'Espèce',
      genus: 'Genre',
      familyBio: 'Famille',
      orderBio: 'Ordre',
      classBio: 'Classe',
      phylum: 'Embranchement',
      kingdom: 'Règne',
      domain: 'Domaine',
      life: 'Vie',
      death: 'Mort',
      birth: 'Naissance',
      ageBio: 'Âge',
      growthBio: 'Croissance',
      developmentBio: 'Développement',
      reproduction: 'Reproduction',
      metabolism: 'Métabolisme',
      homeostasis: 'Homéostasie',
      evolutionBio: 'Évolution',
      adaptation: 'Adaptation',
      mutation: 'Mutation',
      variation: 'Variation',
      diversity: 'Diversité',
      biodiversity: 'Biodiversité',
      ecosystem: 'Écosystème',
      environmentBio: 'Environnement',
      habitat: 'Habitat',
      niche: 'Niche',
      population: 'Population',
      community: 'Communauté',
      biome: 'Biome',
      biosphere: 'Biosphère',
      geology: 'Géologie',
      geography: 'Géographie',
      astronomy: 'Astronomie',
      physics: 'Physique',
      chemistry: 'Chimie',
      biology: 'Biologie',
      mathematics: 'Mathématiques',
      science: 'Science',
      technology: 'Technologie',
      engineering: 'Ingénierie',
      medicine: 'Médecine',
      health: 'Santé',
      disease: 'Maladie',
      illness: 'Maladie',
      sickness: 'Maladie',
      conditionMed: 'Condition',
      symptom: 'Symptôme',
      sign: 'Signe',
      diagnosis: 'Diagnostic',
      prognosis: 'Pronostic',
      treatment: 'Traitement',
      therapy: 'Thérapie',
      medication: 'Médication',
      drug: 'Médicament',
      vaccine: 'Vaccin',
      prevention: 'Prévention',
      cure: 'Remède',
      recovery: 'Rétablissement',
      rehabilitation: 'Réhabilitation',
      wellness: 'Bien-être',
      fitness: 'Forme physique',
      exercise: 'Exercice',
      nutrition: 'Nutrition',
      diet: 'Régime',
      food: 'Nourriture',
      water: 'Eau',
      air: 'Air',
      oxygen: 'Oxygène',
      carbonDioxide: 'Dioxyde de carbone',
      nitrogen: 'Azote',
      hydrogen: 'Hydrogène',
      helium: 'Hélium',
      lithium: 'Lithium',
      beryllium: 'Béryllium',
      boron: 'Bore',
      carbon: 'Carbone',
      nitrogenElem: 'Azote',
      oxygenElem: 'Oxygène',
      fluorine: 'Fluor',
      neon: 'Néon',
      sodium: 'Sodium',
      magnesium: 'Magnésium',
      aluminum: 'Aluminium',
      silicon: 'Silicium',
      phosphorus: 'Phosphore',
      sulfur: 'Soufre',
      chlorine: 'Chlore',
      argon: 'Argon',
      potassium: 'Potassium',
      calcium: 'Calcium',
      scandium: 'Scandium',
      titanium: 'Titane',
      vanadium: 'Vanadium',
      chromium: 'Chrome',
      manganese: 'Manganèse',
      iron: 'Fer',
      cobalt: 'Cobalt',
      nickel: 'Nickel',
      copper: 'Cuivre',
      zinc: 'Zinc',
      gallium: 'Gallium',
      germanium: 'Germanium',
      arsenic: 'Arsenic',
      selenium: 'Sélénium',
      bromine: 'Brome',
      krypton: 'Krypton',
      rubidium: 'Rubidium',
      strontium: 'Strontium',
      yttrium: 'Yttrium',
      zirconium: 'Zirconium',
      niobium: 'Niobium',
      molybdenum: 'Molybdène',
      technetium: 'Technétium',
      ruthenium: 'Ruthénium',
      rhodium: 'Rhodium',
      palladium: 'Palladium',
      silver: 'Argent',
      cadmium: 'Cadmium',
      indium: 'Indium',
      tin: 'Étain',
      antimony: 'Antimoine',
      tellurium: 'Tellure',
      iodine: 'Iode',
      xenon: 'Xénon',
      cesium: 'Césium',
      barium: 'Baryum',
      lanthanum: 'Lanthane',
      cerium: 'Cérium',
      praseodymium: 'Praséodyme',
      neodymium: 'Néodyme',
      promethium: 'Prométhium',
      samarium: 'Samarium',
      europium: 'Europium',
      gadolinium: 'Gadolinium',
      terbium: 'Terbium',
      dysprosium: 'Dysprosium',
      holmium: 'Holmium',
      erbium: 'Erbium',
      thulium: 'Thulium',
      ytterbium: 'Ytterbium',
      lutetium: 'Lutécium',
      hafnium: 'Hafnium',
      tantalum: 'Tantale',
      tungsten: 'Tungstène',
      rhenium: 'Rhénium',
      osmium: 'Osmium',
      iridium: 'Iridium',
      platinum: 'Platine',
      gold: 'Or',
      mercury: 'Mercure',
      thallium: 'Thallium',
      lead: 'Plomb',
      bismuth: 'Bismuth',
      polonium: 'Polonium',
      astatine: 'Astate',
      radon: 'Radon',
      francium: 'Francium',
      radium: 'Radium',
      actinium: 'Actinium',
      thorium: 'Thorium',
      protactinium: 'Protactinium',
      uranium: 'Uranium',
      neptunium: 'Neptunium',
      plutonium: 'Plutonium',
      americium: 'Américium',
      curium: 'Curium',
      berkelium: 'Berkélium',
      californium: 'Californium',
      einsteinium: 'Einsteinium',
      fermium: 'Fermium',
      mendelevium: 'Mendélévium',
      nobelium: 'Nobélium',
      lawrencium: 'Lawrencium',
      rutherfordium: 'Rutherfordium',
      dubnium: 'Dubnium',
      seaborgium: 'Seaborgium',
      bohrium: 'Bohrium',
      hassium: 'Hassium',
      meitnerium: 'Meitnerium',
      darmstadtium: 'Darmstadtium',
      roentgenium: 'Roentgenium',
      copernicium: 'Copernicium',
      nihonium: 'Nihonium',
      flerovium: 'Flérovium',
      moscovium: 'Moscovium',
      livermorium: 'Livermorium',
      tennessine: 'Tennesse',
      oganesson: 'Oganesson'
    },
    en: {
      // Navigation
      dashboard: 'Dashboard',
      team: 'Team',
      demands: 'HR Requests',
      payslip: 'Payslip',
      archives: 'Archives',
      statistics: 'Statistics',
      settings: 'Settings',
      visa: 'Visa Requests',
      logout: 'Logout',
      language: 'Language',
      
      // Header et titres
      appTitle: 'HR Manager',
      appSubtitle: 'Human Resources Management',
      lastUpdate: 'Last update',
      welcome: 'Welcome',
      overview: 'Overview',
      details: 'Details',
      actions: 'Actions',
      quickActions: 'Quick Actions',
      summary: 'Summary',
      
      // Dashboard
      totalEmployees: 'Total Employees',
      newThisMonth: 'New This Month',
      contractsToRenew: 'Contracts to Renew',
      totalSalary: 'Total Salary Mass',
      archivesCount: 'Archived Employees',
      manageTeam: 'Manage Team',
      viewStatistics: 'View Statistics',
      viewArchives: 'View Archives',
      exportData: 'Export Data',
      activeGrowth: 'Active growth',
      stableThisMonth: 'Stable this month',
      next30Days: 'In the next 30 days',
      monthlyGross: 'Monthly gross salary total',
      formerEmployees: 'Former employees',
      
      // Team
      employeeManagement: 'Team Management',
      consultEmployees: 'View and manage your active employees information',
      searchPlaceholder: 'Search by name, first name, position or employee ID...',
      employeesFound: 'employee(s) found',
      refresh: 'Refresh',
      addEmployee: 'Add Employee',
      noResults: 'No employee found',
      addFirstEmployee: 'Add first employee',
      
      // Employee Modal
      employeeDetails: 'Employee Details',
      personalInfo: 'Personal Information',
      professionalInfo: 'Professional Information',
      emailContacts: 'Email Contacts',
      documents: 'Documents',
      editInfo: 'Edit Information',
      save: 'Save',
      cancel: 'Cancel',
      changePhoto: 'Change photo',
      departureDate: 'Departure date',
      archiveEmployee: 'Archive employee',
      archiveHint: 'Add a departure date to be able to archive the employee',
      addUpdateDossier: 'Add/Update HR dossier',
      noDocument: 'No document',
      requiredField: 'This field is required',
      optional: 'Optional',
      
      // Add Employee Modal
      addNewEmployee: 'Add New Employee',
      employeePhoto: 'Employee photo',
      clickToSelectPhoto: 'Click to select a photo',
      photoRequirements: 'JPG, PNG, GIF (max 5MB)',
      choosePhoto: 'Choose photo',
      removePhoto: 'Remove',
      employeeEmail: 'Employee email',
      supervisor1Email: 'Supervisor 1 email',
      supervisor2Email: 'Supervisor 2 email',
      idNumber: 'ID Number',
      passport: 'Passport',
      birthDate: 'Birth Date',
      position: 'Position',
      department: 'Site/Department',
      contractType: 'Contract Type',
      startDate: 'Start Date',
      grossSalary: 'Gross Salary',
      createEmployee: 'Create Employee',
      uploadingPhoto: 'Uploading photo...',
      creating: 'Creating...',
      
      // Archive Modal
      archiveEmployeeTitle: 'Archive Employee',
      uploadDepartureInterview: 'Upload Departure Interview PDF',
      required: 'Required',
      attachReport: 'Attach departure interview report in PDF format',
      clickToSelectFile: 'Click to select a file',
      dragDropHere: 'or drag and drop your PDF file here',
      pdfOnly: 'PDF format only',
      uploading: 'Uploading',
      doNotClose: 'Do not close this window during upload...',
      uploadSuccess: 'PDF uploaded successfully!',
      previewPDF: 'Preview PDF',
      changeFile: 'Change file',
      confirmArchive: 'Archive employee',
      processing: 'Processing...',
      archiveNote: 'Archiving will take effect immediately after confirmation',
      
      // Archives Page
      archivedEmployees: 'Archived Employees',
      formerEmployeesList: 'List of employees who left the company',
      withInterview: 'With Interview',
      departureInterviews: 'Departure Interviews',
      searchArchives: 'Search in archives...',
      backToTeam: 'Back to team',
      noArchives: 'No archived employee',
      archivedWillAppear: 'Archived employees will appear here after their departure',
      viewActiveEmployees: 'View active employees',
      departure: 'Departure',
      viewInterview: 'View interview',
      archiveDetails: 'Archived Employee Details',
      archiveDocuments: 'Archive Documents',
      mainArchiveDocument: 'Main archive document',
      legacyFormat: 'Legacy format document',
      completeHRFile: 'Complete HR File',
      noDocumentsAvailable: 'No archive document available',
      archivedWithoutDocument: 'Employee was archived without departure interview document',
      archiveInfo: 'Archive Information',
      lastUpdate: 'Last update',
      creationDate: 'Creation date',
      documentsKept: 'Archive documents are kept for a minimum of 5 years',
      printDetails: 'Print',
      backToList: 'Back to list',
      
      // Statistics
      statisticsDashboard: 'Statistics Dashboard',
      hrAnalysis: 'Detailed analysis of your human resources',
      departmentDistribution: 'Department Distribution',
      contractTypes: 'Contract Types',
      salaryAnalysis: 'Salary Analysis',
      recentHires: 'Recent Hires',
      minimumSalary: 'Minimum Salary',
      maximumSalary: 'Maximum Salary',
      medianSalary: 'Median Salary',
      averageSalary: 'Average Salary',
      exportDataPDF: 'Export to PDF',
      exportStatisticsExcel: 'Export Statistics Excel',
      exportEmployeesExcel: 'Export Employees Excel',
      noHiresThisMonth: 'No hires this month',
      
      // Demandes RH
      hrRequests: 'HR Requests Consultation',
      requestTracking: 'Visualization and tracking of employee requests',
      searchFilters: 'Search filters',
      allStatus: 'All status',
      allTypes: 'All types',
      allDates: 'All dates',
      fromDate: 'From date',
      toDate: 'To date',
      activeFilters: 'Active filters',
      clearFilters: 'Clear filters',
      exportExcel: 'Export Excel',
      totalRequests: 'Total requests',
      pending: 'Pending',
      approved: 'Approved',
      refused: 'Refused',
      results: 'Results',
      page: 'Page',
      of: 'of',
      noRequests: 'No request found',
      noMatchingCriteria: 'No request matches your search criteria',
      showAllRequests: 'Show all requests',
      leaveType: 'Leave type',
      approvalProcess: 'Approval process',
      createdOn: 'Created on',
      lastUpdated: 'Last updated',
      refusalComment: 'Refusal comment',
      viewDetails: 'View full details',
      generalInfo: 'General information',
      employeeInfo: 'Employee information',
      requestDetails: 'Request details',
      startDateReq: 'Start date',
      returnDate: 'Return date',
      departureTime: 'Departure time',
      returnTime: 'Return time',
      travelExpenses: 'Travel expenses',
      halfDay: 'Half day',
      close: 'Close',
      supervisor1: 'Supervisor 1',
      supervisor2: 'Supervisor 2',
      notAssigned: 'Not assigned',
      notRequired: 'Not applicable',
      
      // Fiche de Paie
      payslip: 'Payslip',
      autoSendPayslips: 'Automatic sending of payslips to employees',
      importPDF: 'Import PDF file',
      pdfDescription: 'PDF must contain one payslip per page. Each slip must have the employee ID (MATR.).',
      choosePDF: 'Choose PDF file',
      processAndSend: 'Process and send',
      processingInProgress: 'Processing in progress...',
      extractingMatricules: 'Extracting IDs and sending emails...',
      mayTakeSeveralMinutes: 'This may take several minutes depending on number of pages',
      processingComplete: 'Processing complete',
      sheetsSent: 'sheet(s) sent out of',
      pages: 'page(s)',
      errorDetails: 'Error details',
      employeeMatricule: 'Employee ID',
      employee: 'Employee',
      error: 'Error',
      
      // Login
      login: 'Login',
      loginToYourAccount: 'Log in to your account',
      email: 'Email',
      password: 'Password',
      forgotPassword: 'Forgot password?',
      resetPassword: 'Reset password',
      enterEmailForNewPassword: 'Enter your email address to receive a new password.',
      sendNewPassword: 'Send new password',
      backToLogin: 'Back to login',
      temporaryPasswordNote: 'An email with a new password will be sent to you. This password is temporary, change it after login. Check your spam if you don\'t receive the email.',
      appDescription: 'Human resources management application',
      version: 'Version',
      
      // Settings
      settings: 'Settings',
      managePreferences: 'Manage your application preferences and settings',
      chooseLanguage: 'Choose application display language',
      currentLanguage: 'Current language',
      changeEffectiveImmediately: 'Change takes effect immediately throughout the application',
      notifications: 'Notifications',
      configureNotifications: 'Configure how you receive notifications',
      emailNotifications: 'Email notifications',
      receiveAlertsByEmail: 'Receive important alerts by email',
      pushNotifications: 'Push notifications',
      realTimeAlerts: 'Real-time alerts in the application',
      weeklyReport: 'Weekly report',
      weeklySummaryEmail: 'Receive weekly summary by email',
      about: 'About',
      userGuide: 'User guide',
      technicalSupport: 'Technical support',
      termsOfUse: 'Terms of use',
      privacyPolicy: 'Privacy policy',
      saveChanges: 'Save changes',
      restoreDefaults: 'Restore defaults',
      
      // Common (simplified - same keys as French but English values)
      loading: 'Loading...',
      yes: 'Yes',
      no: 'No',
      na: 'N/A',
      success: 'Success',
      warning: 'Warning',
      info: 'Information',
      confirm: 'Confirm',
      delete: 'Delete',
      edit: 'Edit',
      view: 'View',
      download: 'Download',
      upload: 'Upload',
      search: 'Search',
      filter: 'Filter',
      sort: 'Sort',
      previous: 'Previous',
      next: 'Next',
      first: 'First',
      last: 'Last',
      today: 'Today',
      yesterday: 'Yesterday',
      thisWeek: 'This week',
      thisMonth: 'This month',
      thisYear: 'This year',
      all: 'All',
      none: 'None',
      unknown: 'Unknown',
      notAvailable: 'Not available',
      notSpecified: 'Not specified',
      add: 'Add',
      remove: 'Remove',
      update: 'Update',
      create: 'Create',
      cancel: 'Cancel',
      save: 'Save',
      close: 'Close',
      back: 'Back',
      nextStep: 'Next step',
      finish: 'Finish',
      print: 'Print',
      export: 'Export',
      import: 'Import',
      refresh: 'Refresh',
      reset: 'Reset',
      apply: 'Apply',
      select: 'Select',
      choose: 'Choose',
      browse: 'Browse',
      dragAndDrop: 'Drag and drop',
      or: 'or',
      and: 'and',
      with: 'with',
      without: 'without',
      per: 'per',
      total: 'Total',
      average: 'Average',
      minimum: 'Minimum',
      maximum: 'Maximum',
      median: 'Median',
      count: 'Count',
      percentage: 'Percentage',
      ratio: 'Ratio',
      status: 'Status',
      type: 'Type',
      date: 'Date',
      time: 'Time',
      datetime: 'Date and time',
      name: 'Name',
      firstName: 'First name',
      lastName: 'Last name',
      fullName: 'Full name',
      emailAddress: 'Email address',
      phone: 'Phone',
      address: 'Address',
      city: 'City',
      country: 'Country',
      postCode: 'Postal code',
      description: 'Description',
      comments: 'Comments',
      notes: 'Notes',
      remarks: 'Remarks',
      attachment: 'Attachment',
      file: 'File',
      document: 'Document',
      image: 'Image',
      photo: 'Photo',
      video: 'Video',
      audio: 'Audio',
      link: 'Link',
      url: 'URL',
      size: 'Size',
      format: 'Format',
      extension: 'Extension',
      dimensions: 'Dimensions',
      resolution: 'Resolution',
      quality: 'Quality',
      settings: 'Settings',
      preferences: 'Preferences',
      configuration: 'Configuration',
      options: 'Options',
      advanced: 'Advanced',
      basic: 'Basic',
      simple: 'Simple',
      complex: 'Complex',
      easy: 'Easy',
      difficult: 'Difficult',
      quick: 'Quick',
      slow: 'Slow',
      fast: 'Fast',
      new: 'New',
      old: 'Old',
      recent: 'Recent',
      current: 'Current',
      previous: 'Previous',
      next: 'Next',
      future: 'Future',
      past: 'Past',
      present: 'Present',
      active: 'Active',
      inactive: 'Inactive',
      enabled: 'Enabled',
      disabled: 'Disabled',
      visible: 'Visible',
      hidden: 'Hidden',
      public: 'Public',
      private: 'Private',
      shared: 'Shared',
      personal: 'Personal',
      professional: 'Professional',
      business: 'Business',
      contactInfo: 'Contact information',
      financialInfo: 'Financial information',
      legalInfo: 'Legal information'
    },
    zh: {
      // Navigation
      dashboard: '仪表板',
      team: '团队',
      demands: '人力资源请求',
      payslip: '工资单',
      archives: '档案',
      statistics: '统计',
      settings: '设置',
      visa: '签证请求',
      logout: '登出',
      language: '语言',
      
      // Header et titres
      appTitle: '人力资源经理',
      appSubtitle: '人力资源管理',
      lastUpdate: '最后更新',
      welcome: '欢迎',
      overview: '概览',
      details: '详情',
      actions: '操作',
      quickActions: '快速操作',
      summary: '摘要',
      
      // Dashboard
      totalEmployees: '员工总数',
      newThisMonth: '本月新增',
      contractsToRenew: '待续约合同',
      totalSalary: '薪资总额',
      archivesCount: '归档员工',
      manageTeam: '管理团队',
      viewStatistics: '查看统计',
      viewArchives: '查看档案',
      exportData: '导出数据',
      activeGrowth: '活跃增长',
      stableThisMonth: '本月稳定',
      next30Days: '未来30天内',
      monthlyGross: '月度总薪资',
      formerEmployees: '前员工',
      
      // Team
      employeeManagement: '团队管理',
      consultEmployees: '查看和管理您的在职员工信息',
      searchPlaceholder: '按姓名、职位或员工ID搜索...',
      employeesFound: '名员工找到',
      refresh: '刷新',
      addEmployee: '添加员工',
      noResults: '未找到员工',
      addFirstEmployee: '添加第一名员工',
      
      // Employee Modal
      employeeDetails: '员工详情',
      personalInfo: '个人信息',
      professionalInfo: '职业信息',
      emailContacts: '电子邮件联系人',
      documents: '文件',
      editInfo: '编辑信息',
      save: '保存',
      cancel: '取消',
      changePhoto: '更换照片',
      departureDate: '离职日期',
      archiveEmployee: '归档员工',
      archiveHint: '添加离职日期以归档员工',
      addUpdateDossier: '添加/更新人力资源档案',
      noDocument: '无文件',
      requiredField: '此字段为必填项',
      optional: '可选',
      
      // Add Employee Modal
      addNewEmployee: '添加新员工',
      employeePhoto: '员工照片',
      clickToSelectPhoto: '点击选择照片',
      photoRequirements: 'JPG、PNG、GIF格式（最大5MB）',
      choosePhoto: '选择照片',
      removePhoto: '删除',
      employeeEmail: '员工邮箱',
      supervisor1Email: '主管1邮箱',
      supervisor2Email: '主管2邮箱',
      idNumber: '身份证号',
      passport: '护照',
      birthDate: '出生日期',
      position: '职位',
      department: '地点/部门',
      contractType: '合同类型',
      startDate: '开始日期',
      grossSalary: '基本工资',
      createEmployee: '创建员工',
      uploadingPhoto: '上传照片中...',
      creating: '创建中...',
      
      // Archive Modal
      archiveEmployeeTitle: '归档员工',
      uploadDepartureInterview: '上传离职面试PDF',
      required: '必需',
      attachReport: '附上PDF格式的离职面试报告',
      clickToSelectFile: '点击选择文件',
      dragDropHere: '或将PDF文件拖放到此处',
      pdfOnly: '仅限PDF格式',
      uploading: '上传中',
      doNotClose: '上传期间请勿关闭窗口...',
      uploadSuccess: 'PDF上传成功！',
      previewPDF: '预览PDF',
      changeFile: '更换文件',
      confirmArchive: '归档员工',
      processing: '处理中...',
      archiveNote: '确认后归档将立即生效',
      
      // Archives Page
      archivedEmployees: '已归档员工',
      formerEmployeesList: '已离职员工列表',
      withInterview: '有面试记录',
      departureInterviews: '离职面试',
      searchArchives: '在档案中搜索...',
      backToTeam: '返回团队',
      noArchives: '无归档员工',
      archivedWillAppear: '员工离职后将在此处显示',
      viewActiveEmployees: '查看在职员工',
      departure: '离职',
      viewInterview: '查看面试',
      archiveDetails: '归档员工详情',
      archiveDocuments: '归档文件',
      mainArchiveDocument: '主要归档文件',
      legacyFormat: '旧格式文件',
      completeHRFile: '完整人力资源文件',
      noDocumentsAvailable: '无归档文件可用',
      archivedWithoutDocument: '员工归档时无离职面试文件',
      archiveInfo: '归档信息',
      lastUpdate: '最后更新',
      creationDate: '创建日期',
      documentsKept: '归档文件至少保存5年',
      printDetails: '打印',
      backToList: '返回列表',
      
      // Statistics
      statisticsDashboard: '统计仪表板',
      hrAnalysis: '人力资源详细分析',
      departmentDistribution: '部门分布',
      contractTypes: '合同类型',
      salaryAnalysis: '薪资分析',
      recentHires: '近期招聘',
      minimumSalary: '最低薪资',
      maximumSalary: '最高薪资',
      medianSalary: '中位薪资',
      averageSalary: '平均薪资',
      exportDataPDF: '导出为PDF',
      exportStatisticsExcel: '导出统计Excel',
      exportEmployeesExcel: '导出员工Excel',
      noHiresThisMonth: '本月无招聘',
      
      // Demandes RH
      hrRequests: '人力资源请求咨询',
      requestTracking: '员工请求的查看和跟踪',
      searchFilters: '搜索过滤器',
      allStatus: '所有状态',
      allTypes: '所有类型',
      allDates: '所有日期',
      fromDate: '从日期',
      toDate: '至日期',
      activeFilters: '活动过滤器',
      clearFilters: '清除过滤器',
      exportExcel: '导出Excel',
      totalRequests: '总请求数',
      pending: '待处理',
      approved: '已批准',
      refused: '已拒绝',
      results: '结果',
      page: '页',
      of: '共',
      noRequests: '未找到请求',
      noMatchingCriteria: '无请求符合您的搜索条件',
      showAllRequests: '显示所有请求',
      leaveType: '请假类型',
      approvalProcess: '审批流程',
      createdOn: '创建于',
      lastUpdated: '最后更新',
      refusalComment: '拒绝评论',
      viewDetails: '查看完整详情',
      generalInfo: '一般信息',
      employeeInfo: '员工信息',
      requestDetails: '请求详情',
      startDateReq: '开始日期',
      returnDate: '返回日期',
      departureTime: '出发时间',
      returnTime: '返回时间',
      travelExpenses: '差旅费',
      halfDay: '半天',
      close: '关闭',
      supervisor1: '主管1',
      supervisor2: '主管2',
      notAssigned: '未分配',
      notRequired: '不适用',
      
      // Fiche de Paie
      payslip: '工资单',
      autoSendPayslips: '自动向员工发送工资单',
      importPDF: '导入PDF文件',
      pdfDescription: 'PDF每页必须包含一张工资单。每张工资单必须有员工ID（MATR.）。',
      choosePDF: '选择PDF文件',
      processAndSend: '处理并发送',
      processingInProgress: '处理进行中...',
      extractingMatricules: '提取ID并发送电子邮件...',
      mayTakeSeveralMinutes: '根据页数可能需要几分钟',
      processingComplete: '处理完成',
      sheetsSent: '张工资单已发送，共',
      pages: '页',
      errorDetails: '错误详情',
      employeeMatricule: '员工ID',
      employee: '员工',
      error: '错误',
      
      // Login
      login: '登录',
      loginToYourAccount: '登录您的账户',
      email: '电子邮件',
      password: '密码',
      forgotPassword: '忘记密码？',
      resetPassword: '重置密码',
      enterEmailForNewPassword: '输入您的电子邮件地址以接收新密码。',
      sendNewPassword: '发送新密码',
      backToLogin: '返回登录',
      temporaryPasswordNote: '将向您发送包含新密码的电子邮件。此密码为临时密码，登录后请更改。如果未收到电子邮件，请检查垃圾邮件。',
      appDescription: '人力资源管理应用',
      version: '版本',
      
      // Settings
      settings: '设置',
      managePreferences: '管理您的应用偏好和设置',
      chooseLanguage: '选择应用显示语言',
      currentLanguage: '当前语言',
      changeEffectiveImmediately: '更改将在整个应用中立即生效',
      notifications: '通知',
      configureNotifications: '配置您接收通知的方式',
      emailNotifications: '电子邮件通知',
      receiveAlertsByEmail: '通过电子邮件接收重要警报',
      pushNotifications: '推送通知',
      realTimeAlerts: '应用中的实时警报',
      weeklyReport: '周报',
      weeklySummaryEmail: '通过电子邮件接收周报',
      about: '关于',
      userGuide: '用户指南',
      technicalSupport: '技术支持',
      termsOfUse: '使用条款',
      privacyPolicy: '隐私政策',
      saveChanges: '保存更改',
      restoreDefaults: '恢复默认值',
      
      // Common (simplified - same keys as French but Chinese values)
      loading: '加载中...',
      yes: '是',
      no: '否',
      na: '不适用',
      success: '成功',
      warning: '警告',
      info: '信息',
      confirm: '确认',
      delete: '删除',
      edit: '编辑',
      view: '查看',
      download: '下载',
      upload: '上传',
      search: '搜索',
      filter: '过滤',
      sort: '排序',
      previous: '上一页',
      next: '下一页',
      first: '首页',
      last: '末页',
      today: '今天',
      yesterday: '昨天',
      thisWeek: '本周',
      thisMonth: '本月',
      thisYear: '今年',
      all: '全部',
      none: '无',
      unknown: '未知',
      notAvailable: '不可用',
      notSpecified: '未指定',
      add: '添加',
      remove: '移除',
      update: '更新',
      create: '创建',
      cancel: '取消',
      save: '保存',
      close: '关闭',
      back: '返回',
      nextStep: '下一步',
      finish: '完成',
      print: '打印',
      export: '导出',
      import: '导入',
      refresh: '刷新',
      reset: '重置',
      apply: '应用',
      select: '选择',
      choose: '选择',
      browse: '浏览',
      dragAndDrop: '拖放',
      or: '或',
      and: '和',
      with: '与',
      without: '无',
      per: '每',
      total: '总计',
      average: '平均',
      minimum: '最小',
      maximum: '最大',
      median: '中位数',
      count: '计数',
      percentage: '百分比',
      ratio: '比率',
      status: '状态',
      type: '类型',
      date: '日期',
      time: '时间',
      datetime: '日期时间',
      name: '名称',
      firstName: '名字',
      lastName: '姓氏',
      fullName: '全名',
      emailAddress: '电子邮件地址',
      phone: '电话',
      address: '地址',
      city: '城市',
      country: '国家',
      postCode: '邮政编码',
      description: '描述',
      comments: '评论',
      notes: '备注',
      remarks: '备注',
      attachment: '附件',
      file: '文件',
      document: '文档',
      image: '图片',
      photo: '照片',
      video: '视频',
      audio: '音频',
      link: '链接',
      url: '网址',
      size: '大小',
      format: '格式',
      extension: '扩展名',
      dimensions: '尺寸',
      resolution: '分辨率',
      quality: '质量',
      preferences: '偏好',
      configuration: '配置',
      options: '选项',
      advanced: '高级',
      basic: '基础',
      simple: '简单',
      complex: '复杂',
      easy: '容易',
      difficult: '困难',
      quick: '快速',
      slow: '缓慢',
      fast: '快速',
      new: '新',
      old: '旧',
      recent: '最近',
      current: '当前',
      previous: '上一个',
      next: '下一个',
      future: '未来',
      past: '过去',
      present: '现在',
      active: '活跃',
      inactive: '不活跃',
      enabled: '启用',
      disabled: '禁用',
      visible: '可见',
      hidden: '隐藏',
      public: '公开',
      private: '私有',
      shared: '共享',
      personal: '个人',
      professional: '专业',
      business: '商业',
      contactInfo: '联系信息',
      financialInfo: '财务信息',
      legalInfo: '法律信息'
    }
  };

  const t = (key, params = {}) => {
    let translation = translations[language]?.[key] || key;
    
    // Remplacer les paramètres dans la traduction
    Object.keys(params).forEach(param => {
      translation = translation.replace(`{{${param}}}`, params[param]);
    });
    
    return translation;
  };

  const getAvailableLanguages = () => {
    return [
      { code: 'fr', name: 'Français', flag: '🇫🇷' },
      { code: 'en', name: 'English', flag: '🇬🇧' },
      { code: 'zh', name: '中文', flag: '🇨🇳' }
    ];
  };

  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage, 
      t,
      getAvailableLanguages
    }}>
      {children}
    </LanguageContext.Provider>
  );
};
