import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem('language');
    return savedLanguage || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  // Traductions complètes
  const translations = {
    fr: {
      // Navigation
      dashboard: 'Tableau de Bord',
      team: 'Équipe',
      demands: 'Demandes RH',
      payslip: 'Fiche de Paie',
      archives: 'Archives',
      statistics: 'Statistiques',
      settings: 'Paramètres',
      visa: 'Demandes Visa',
      logout: 'Déconnexion',
      language: 'Langue',
      
      // Header et titres
      appTitle: 'RH Manager',
      appSubtitle: 'Gestion des ressources humaines',
      lastUpdate: 'Dernière mise à jour',
      welcome: 'Bienvenue',
      overview: 'Vue d\'ensemble',
      details: 'Détails',
      actions: 'Actions',
      quickActions: 'Actions Rapides',
      summary: 'Résumé',
      
      // Dashboard
      totalEmployees: 'Effectif Total',
      newThisMonth: 'Nouveaux ce mois',
      contractsToRenew: 'Contrats à renouveler',
      totalSalary: 'Masse Salariale',
      archivesCount: 'Employés Archivés',
      manageTeam: 'Gérer l\'Équipe',
      advancedAnalytics: 'Analyses Avancées',
      viewStatistics: 'Voir les statistiques',
      viewArchives: 'Consulter les archives',
      exportData: 'Exporter les Données',
      activeGrowth: 'Croissance active',
      stableThisMonth: 'Stable ce mois-ci',
      next30Days: 'Dans les 30 prochains jours',
      monthlyGross: 'Salaire brut mensuel total',
      formerEmployees: 'Anciens employés',
      hrisThisMonth: 'Embauches ce mois-ci',
      activeEmployees: 'Employés actifs',
      hiresThisMonth: 'Embauches ce mois',
      cdiContracts: 'Contrats CDI',
      cddContracts: 'Contrats CDD',
      civpContracts: 'Contrats CIVP',
      toRenew: 'À renouveler',
      salaryMass: 'Masse salariale',
      archivedEmployees: 'Employés archivés',
      downloadEmployeeList: 'Télécharger liste employés',
      excelFormat: 'Format Excel',
      generating: 'Génération...',
      exporting: 'Exportation...',
      exportExcel: 'Exporter Excel',
      
      // Team
      employeeManagement: 'Gestion de l\'Équipe',
      consultEmployees: 'Consulter et gérez les informations de vos employés actifs',
      searchPlaceholder: 'Rechercher par nom, prénom ou matricule',
      employeesFound: 'employés trouvés',
      refresh: 'Actualiser',
      addEmployee: 'Ajouter Employé',
      noResults: 'Aucun employé trouvé',
      noResultsForSearch: 'Aucun résultat pour votre recherche',
      noActiveEmployees: 'Aucun employé actif',
      addFirstEmployee: 'Ajouter le premier employé',
      
      // Employee Modal
      employeeDetails: 'Détails de l\'Employé',
      personalInfo: 'Informations Personnelles',
      professionalInfo: 'Informations Professionnelles',
      emailContacts: 'Coordonnées Email',
      documents: 'Documents',
      editInfo: 'Modifier les informations',
      save: 'Sauvegarder',
      cancel: 'Annuler',
      changePhoto: 'Changer la photo',
      departureDate: 'Date de départ',
      archiveEmployee: 'Archiver l\'employé',
      archiveHint: 'Ajouter une date de départ pour pouvoir archiver l\'employé',
      addUpdateDossier: 'Ajouter/Mettre à jour le dossier RH',
      noDocument: 'Aucun document',
      requiredField: 'Ce champ est requis',
      optional: 'Optionnel',
      passportIssueDate: "Date d'émission du passeport",
      passportExpiryDate: "Date d'expiration du passeport",
      employeeID: 'Matricule',
      lastName: 'Nom',
      firstName: 'Prénom',
      birthDate: 'Date de Naissance',
      identification: 'Identification',
      idNumber: 'CIN',
      passport: 'Passeport',
      position: 'Poste',
      department: 'Site/Département',
      contractType: 'Type de Contrat',
      startDate: 'Date Début',
      grossSalary: 'Salaire Brut',
      contactInfo: 'Informations de Contact',
      employeeEmail: 'Email employé',
      supervisor1Email: 'Email Responsable 1',
      supervisor2Email: 'Email Responsable 2',
      hireDate: 'Date d\'embauche',
      contractEndDate: 'Date fin de contrat',
      daysRemaining: 'Jours restants',
      emailNotSpecified: 'Non spécifié',
      contractEndingSoon: 'Contrat se termine bientôt',
      endsOn: 'Termine le',
      since: 'Depuis',
      newPhotoSelected: 'Nouvelle photo sélectionnée',
      hrFile: 'Dossier RH',
      departureInterview: 'Entretien de départ',
      interviewPDF: 'PDF d\'entretien',
      deleteDossier: 'Supprimer le dossier',
      confirmDeleteDossier: 'Confirmer la suppression du dossier',
      confirmDeleteCheckbox: 'Je confirme vouloir supprimer ce dossier RH',
      deleting: 'Suppression...',
      confirmDelete: 'Confirmer la suppression',
      changesSaved: 'Modifications sauvegardées',
      saveError: 'Erreur lors de la sauvegarde',
      dossierDeletedSuccess: 'Dossier RH supprimé avec succès',
      errorDeletingDossier: 'Erreur lors de la suppression du dossier',
      confirmCheckboxRequired: 'Veuillez cocher la case de confirmation',
      notAuthenticated: 'Non authentifié',
      networkError: 'Erreur réseau',
      serverErrorContactAdmin: 'Erreur serveur, contactez l\'administrateur',
      dateFormatError: 'Erreur de format de date',
      archiveError: 'Erreur lors de l\'archivage',
      employeeArchived: 'Employé archivé avec succès',
      addDepartureDateFirst: 'Ajoutez d\'abord une date de départ',
      notPDFConfirm: 'Ce lien ne semble pas être un PDF. Voulez-vous quand même l\'ouvrir?',
      select: 'Sélectionner',
      saving: 'Sauvegarde...',
      
      // Add Employee Modal
      addNewEmployee: 'Ajouter un Nouvel Employé',
      employeePhoto: 'Photo de l\'employé',
      clickToSelectPhoto: 'Cliquez pour sélectionner une photo',
      photoRequirements: 'JPG, PNG, GIF (max 5MB)',
      choosePhoto: 'Choisir une photo',
      removePhoto: 'Supprimer',
      createEmployee: 'Créer Employé',
      uploadingPhoto: 'Upload photo...',
      creating: 'Création...',
      validEmployeeEmail: 'Veuillez entrer un email valide pour l\'employé',
      validSupervisor1Email: 'Veuillez entrer un email valide pour le responsable 1',
      validSupervisor2Email: 'Veuillez entrer un email valide pour le responsable 2',
      fillRequiredFields: 'Veuillez remplir tous les champs obligatoires',
      photoUploadError: 'Erreur lors de l\'upload de la photo',
      photoUploadErrorAlert: 'Impossible d\'uploader la photo, utilisation de l\'avatar par défaut',
      employeeCreated: 'Employé créé avec succès',
      creationError: 'Erreur lors de la création de l\'employé',
      selectImage: 'Veuillez sélectionner une image',
      fileSizeExceeded: 'Le fichier est trop volumineux (max 5MB)',
      headquarters: 'Siège',
      uploadPhoto: 'Uploader une photo',
      optionalForPermanent: 'Optionnel pour CDI',
      
      // Départements
      Commerce: 'Commerce',
      Finance: 'Finance',
      Chiffrage: 'Chiffrage',
      Digitale: 'Digitale',
      Général: 'Général',
      'Logistique Germany': 'Logistique Germany',
      'Logistique Groupe': 'Logistique Groupe',
      Achat: 'Achat',
      Qualité: 'Qualité',
      
      // Archive Modal
      archiveEmployeeTitle: 'Archiver l\'Employé',
      uploadDepartureInterview: 'Télécharger le PDF d\'entretien de départ',
      required: 'Obligatoire',
      attachReport: 'Joignez le rapport d\'entretien de départ au format PDF',
      clickToSelectFile: 'Cliquez pour sélectionner un fichier',
      dragDropHere: 'ou glissez-déposez votre fichier PDF ici',
      pdfOnly: 'Format PDF uniquement',
      uploading: 'Envoi en cours',
      doNotClose: 'Ne fermez pas cette fenêtre pendant l\'upload...',
      uploadSuccess: 'PDF téléchargé avec succès !',
      previewPDF: 'Aperçu du PDF',
      changeFile: 'Changer le fichier',
      confirmArchive: 'Archiver l\'employé',
      processing: 'Traitement en cours...',
      archiveNote: 'L\'archivage prendra effet immédiatement après confirmation',
      
      // Archives Page
      archivedEmployees: 'Archives des Employés',
      formerEmployeesList: 'Liste des employés ayant quitté l\'entreprise',
      withInterview: 'Avec Entretien',
      departureInterviews: 'Entretiens de départ',
      searchArchives: 'Rechercher dans les archives...',
      backToTeam: 'Retour à l\'équipe',
      noArchives: 'Aucun employé archivé',
      archivedWillAppear: 'Les employés archivés apparaîtront ici après leur départ',
      viewActiveEmployees: 'Voir les employés actifs',
      departure: 'Départ',
      viewInterview: 'Voir l\'entretien',
      archiveDetails: 'Détails de l\'Employé Archivé',
      archiveDocuments: 'Documents d\'Archive',
      mainArchiveDocument: 'Document principal d\'archive',
      legacyFormat: 'Ancien format de document',
      completeHRFile: 'Dossier RH complet',
      noDocumentsAvailable: 'Aucun document d\'archive disponible',
      archivedWithoutDocument: 'L\'employé a été archivé sans document d\'entretien de départ',
      archiveInfo: 'Informations d\'Archivage',
      creationDate: 'Date de création',
      documentsKept: 'Les documents d\'archive sont conservés pour une durée de 5 ans minimum',
      printDetails: 'Imprimer',
      backToList: 'Retour à la liste',
      errorLoadingArchives: 'Erreur lors du chargement des archives',
      errorLoadingArchivesAlert: 'Erreur lors du chargement des employés archivés',
      noDepartureInterviewAvailable: 'Aucun entretien de départ disponible',
      invalidInterviewLink: 'Lien d\'entretien invalide',
      errorOpeningPDF: 'Erreur lors de l\'ouverture du PDF',
      loadingArchives: 'Chargement des archives...',
      totalArchived: 'Total archivés',
      
      // ArchiveEmployeeModal
      career: 'Carrière',
      documentStoredOnServer: 'Document stocké sur le serveur',
      externalLink: 'Lien externe',
      pdfOpenError: 'Erreur ouverture PDF',
      cannotOpenDocument: 'Impossible d\'ouvrir le document. Le lien peut être invalide.',
      noHRDossierAvailable: 'Aucun dossier RH disponible',
      invalidURL: 'Le lien n\'est pas une URL valide',
      link: 'Lien',
      opening: 'Ouverture',
      openPDF: 'Ouvrir le PDF',
      legacy: 'ancien',
      openLink: 'Ouvrir le lien',
      hrDossier: 'Dossier ressources humaines',
      consultDossier: 'Consulter le dossier',
      days: 'jours',
      url: 'URL',
      status: 'Statut',
      archived: 'Archivé',
      close: 'Fermer',
      print: 'Imprimer',
      
      // Statistics
      statisticsDashboard: 'Tableau de Bord Statistiques',
      hrAnalysis: 'Analyse détaillée de vos ressources humaines',
      departmentDistribution: 'Répartition par Département',
      contractTypes: 'Types de Contrat',
      salaryAnalysis: 'Analyse des Salaires',
      recentHires: 'Dernières Embauches',
      minimumSalary: 'Salaire Minimum',
      maximumSalary: 'Salaire Maximum',
      medianSalary: 'Salaire Médian',
      averageSalary: 'Salaire Moyen',
      exportDataPDF: 'Exporter en PDF',
      exportStatisticsExcel: 'Exporter Statistiques Excel',
      exportEmployeesExcel: 'Exporter Liste Employés Excel',
      noHiresThisMonth: 'Aucune embauche ce mois-ci',
      errorLoadingStats: 'Erreur lors du chargement des statistiques',
      loadingStatistics: 'Chargement des statistiques...',
      departments: 'Départements',
      activeSites: 'Sites actifs',
      perEmployee: 'Par employé',
      detailedStats: 'Statistiques détaillées',
      viewTrends: 'Voir tendances',
      
      // Demandes RH
      hrRequests: 'Consultation des Demandes RH',
      requestTracking: 'Visualisation et suivi des demandes des collaborateurs',
      searchFilters: 'Filtres de recherche',
      allStatus: 'Tous les statuts',
      allTypes: 'Tous les types',
      allDates: 'Toutes les dates',
      fromDate: 'À partir du',
      toDate: 'Jusqu\'au',
      activeFilters: 'Filtres actifs',
      clearFilters: 'Effacer filtres',
      exportExcel: 'Exporter Excel',
      totalRequests: 'Total demandes',
      pending: 'En attente',
      approved: 'Approuvées',
      refused: 'Refusées',
      results: 'Résultats',
      page: 'Page',
      of: 'sur',
      noRequests: 'Aucune demande trouvée',
      noMatchingCriteria: 'Aucune demande ne correspond à vos critères de recherche',
      showAllRequests: 'Afficher toutes les demandes',
      leaveType: 'Type de congé',
      approvalProcess: 'Processus d\'approbation',
      createdOn: 'Créé le',
      lastUpdated: 'Dernière mise à jour',
      refusalComment: 'Commentaire de refus',
      viewDetails: 'Voir les détails complets',
      generalInfo: 'Informations générales',
      employeeInfo: 'Informations employé',
      requestDetails: 'Détails de la demande',
      startDateReq: 'Date début',
      returnDate: 'Date retour',
      departureTime: 'Heure départ',
      returnTime: 'Heure retour',
      travelExpenses: 'Frais déplacement',
      halfDay: 'Demi-journée',
      supervisor1: 'Responsable 1',
      supervisor2: 'Responsable 2',
      notAssigned: 'Non assigné',
      notRequired: 'Non applicable',
      missingAuthToken: 'Token d\'authentification manquant',
      serverError: 'Erreur serveur',
      errorFetchingRequests: 'Erreur lors de la récupération des demandes',
      connectionError: 'Erreur de connexion',
      loadingRequests: 'Chargement des demandes...',
      applyingFilters: 'Application des filtres...',
      loadingError: 'Erreur de chargement',
      noRequestsAvailable: 'Aucune demande disponible',
      email: 'Email',
      title: 'Titre',
      type: 'Type',
      employee: 'Employé',
      na: 'N/A',
      emailNotAvailable: 'Email non disponible',
      yes: 'Oui',
      justNow: 'À l\'instant',
      minutesAgo: 'min',
      hoursAgo: 'h',
      noNewNotifications: 'Aucune nouvelle notification',
      notifications: 'Notifications',
      loading: 'Chargement...',
      viewAll: 'Voir toutes les demandes',
      
      // Fiche de Paie
      payslip: 'Fiche de Paie',
      autoSendPayslips: 'Envoi automatique des fiches de paie aux employés',
      importPDF: 'Importer un fichier PDF',
      pdfDescription: 'Le PDF doit contenir une fiche de paie par page. Chaque fiche doit avoir le matricule de l\'employé (MATR.).',
      choosePDF: 'Choisir un fichier PDF',
      processAndSend: 'Traiter et envoyer',
      processingInProgress: 'Traitement en cours...',
      extractingMatricules: 'Extraction des matricules et envoi des emails...',
      mayTakeSeveralMinutes: 'Cela peut prendre plusieurs minutes selon le nombre de pages',
      processingComplete: 'Traitement terminé',
      sheetsSent: 'fiche(s) envoyée(s) sur',
      pages: 'page(s)',
      errorDetails: 'Détails des erreurs',
      employeeMatricule: 'Matricule',
      error: 'Erreur',
      invalidPDF: 'Veuillez sélectionner un fichier PDF valide',
      selectPDF: 'Veuillez sélectionner un fichier PDF',
      processingError: 'Erreur lors du traitement',
      uploadError: 'Erreur lors de l\'upload',
      fileProcessingError: 'Erreur lors du traitement du fichier',
      
      // Login
      login: 'Connexion',
      loginToYourAccount: 'Connectez-vous à votre espace',
      password: 'Mot de passe',
      forgotPassword: 'Mot de passe oublié ?',
      resetPassword: 'Réinitialiser le mot de passe',
      enterEmailForNewPassword: 'Entrez votre adresse email pour recevoir un nouveau mot de passe.',
      sendNewPassword: 'Envoyer un nouveau mot de passe',
      backToLogin: 'Retour à la connexion',
      temporaryPasswordNote: 'Un email contenant un nouveau mot de passe vous sera envoyé. Ce mot de passe est temporaire, changez-le après connexion. Vérifiez vos spams si vous ne recevez pas l\'email.',
      appDescription: 'Application de gestion des ressources humaines',
      version: 'Version',
      emailPasswordIncorrect: 'Email ou mot de passe incorrect',
      loggingIn: 'Connexion en cours...',
      sending: 'Envoi en cours...',
      yourPassword: 'Votre mot de passe',
      
      // Settings
      settings: 'Paramètres',
      managePreferences: 'Gérez vos préférences et paramètres de l\'application',
      chooseLanguage: 'Choisissez la langue d\'affichage de l\'application',
      currentLanguage: 'Langue actuelle',
      changeEffectiveImmediately: 'Le changement prend effet immédiatement sur toute l\'application',
      notifications: 'Notifications',
      configureNotifications: 'Configurez comment vous recevez les notifications',
      emailNotifications: 'Notifications par email',
      receiveAlertsByEmail: 'Recevez les alertes importantes par email',
      pushNotifications: 'Notifications push',
      realTimeAlerts: 'Alertes en temps réel dans l\'application',
      weeklyReport: 'Rapport hebdomadaire',
      weeklySummaryEmail: 'Recevez un résumé hebdomadaire par email',
      about: 'À propos',
      userGuide: 'Guide d\'utilisation',
      technicalSupport: 'Support technique',
      termsOfUse: 'Conditions d\'utilisation',
      privacyPolicy: 'Politique de confidentialité',
      saveChanges: 'Enregistrer les modifications',
      restoreDefaults: 'Restaurer les paramètres par défaut',
      languageChangedTo: 'Langue changée en',
      defaultLanguage: 'Langue par défaut',
      englishLanguage: 'English language',
      chineseLanguage: 'Chinese language',
      
      // Visa
      visaTitle: 'Dossiers Visa France',
      visaSubtitleDashboard: 'Gestion des demandes de visa professionnel - Tableau de bord',
      visaSubtitleDetail: 'Suivi détaillé du dossier visa',
      visaBackToDashboard: 'Retour au dashboard',
      visaStepsDocsValidated: 'Documents validés',
      visaStepsReadyToSubmit: 'Prêt pour dépôt',
      visaStepsResult: 'Résultat visa',
      docStatusMissing: 'Manquant',
      docStatusUploaded: 'Uploadé',
      docStatusRejected: 'Refusé',
      docStatusReceivedPhysical: 'Reçu physiquement',
      visaDocTypeBring: 'À apporter',
      visaDocTypeSpecificEmail: 'Email spécifique',
      visaDocTypeBooking: 'Booking.com',
      visaDocTypeFranceVisas: 'France-Visas',
      visaDocTypePdfGeneration: 'Génération PDF',
      visaDocTypeUploadPdf: 'Upload PDF',
      visaOneFile: 'dossier',
      visaManyFiles: 'dossiers',
      visaEmployee: 'Employé',
      visaStatus: 'Statut',
      visaReason: 'Motif',
      visaDeparture: 'Départ',
      visaReturn: 'Retour',
      visaProgress: 'Progress',
      visaVisaNumberShort: 'N° Visa',
      visaValidity: 'Validité',
      visaActions: 'Actions',
      visaConsult: 'Consulter',
      visaNoFileInList: 'Aucun dossier dans cette liste',
      visaCreateNewToStart: 'Créez un nouveau dossier pour commencer',
      visaSearchPlaceholder: 'Rechercher un employé ou un motif...',
      visaFilterStatus: 'Statut',
      visaOneFileFound: 'dossier trouvé',
      visaFilesFound: 'dossiers trouvés',
      visaSectionInProgress: '📋 Dossiers en cours',
      visaSectionReadyToSubmit: '✅ Dossiers prêts pour dépôt',
      visaSectionGranted: '🎉 Visa accordé',
      visaSectionRefused: '❌ Visa refusé',
      visaStatusInProgress: 'En cours',
      visaStatusReadyToSubmit: 'Prêt pour dépôt',
      visaStatusGranted: 'Visa accordé',
      visaStatusRefused: 'Visa refusé',
      visaKpiInProgress: 'Dossiers en cours',
      visaKpiReadyToSubmit: 'Prêts pour dépôt',
      visaKpiGranted: 'Visa accordé',
      visaKpiRefused: 'Visa refusé',
      visaNewFile: 'Nouveau dossier',
      visaCreateNewFile: 'Créer un nouveau dossier visa',
      visaFullName: 'Nom & Prénom',
      visaEmployeesGroupLabel: 'Employees - STS',
      visaCreateFile: 'Créer le dossier',
      visaCancel: 'Annuler',
      visaEmployeeGeneric: 'Employé',
      visaFillAllRequired: 'Merci de remplir tous les champs obligatoires.',
      visaReturnDateAfterDeparture: 'La date de retour doit être >= date de départ.',
      visaCreateFileLoading: 'Création du dossier…',
      visaFileCreatedEmailSent: 'Dossier créé. Email envoyé à',
      visaFileCreatedEmailNotSent: 'Dossier créé, mais email NON envoyé à',
      visaCreateError: 'Erreur création dossier',
      visaLoadingFiles: 'Chargement des dossiers visa…',
      visaFileSummary: 'Résumé du dossier',
      visaTripReason: 'Motif du déplacement',
      visaFileStatus: 'Statut dossier',
      visaDocsProvidedPct: '% des documents requis sont fournis',
      visaDocsProvidedCountLine: 'documents requis fournis',
      visaMissingDocs: 'manquants',
      visaPhysicalToBring: 'à apporter physiquement',
      visaReadyToSubmitBtn: 'Prêt pour dépôt',
      visaDecisionTitle: 'Décision visa',
      visaGrantedBtn: 'Visa accordé',
      visaRefusedBtn: 'Visa refusé',
      visaResultLockedHint: 'Le résultat du visa est disponible après "Prêt pour dépôt".',
      visaFileClosedHint: 'Dossier clôturé : résultat final verrouillé.',
      visaFileClosed: 'Dossier clôturé',
      visaFileDocs: 'Documents du dossier',
      visaDoc: 'Document',
      visaType: 'Type',
      visaSendEmailBtn: 'Envoi mail',
      visaUploadPdfBtn: 'Upload PDF',
      visaPreviewBtn: 'Aperçu',
      visaFillFormBtn: 'Remplir formulaire',
      visaUploadReceiptBtn: 'Upload récépissé',
      visaPreviewPdfBtn: 'Aperçu PDF',
      visaBookHotelBtn: 'Réserver hôtel',
      visaGeneratePdfBtn: 'Générer PDF',
      visaReceivedBtn: 'Reçu',
      visaAllDocsRequiredBeforeReady: 'Tous les documents requis doivent être fournis avant de marquer comme prêt pour dépôt.',
      docMarkedReceivedPhysical: 'Document marqué comme reçu physiquement.',
      visaMissingPdf: 'Aucun PDF uploadé.',
      visaMissingReceiptPdf: 'Aucun récépissé PDF uploadé.',
      visaMissingBookingPdf: 'Aucun PDF de réservation uploadé.',
      visaNoGeneratedFile: 'Aucun fichier généré.',
      visaOpenPdfToPrint: 'Ouverture du PDF pour impression…',
      visaPrintPdfError: 'Erreur impression PDF',
      visaPrintDocs: '🖨 Imprimer les documents',
      visaFillVisaNumberAndDates: 'Merci de remplir numéro visa + dates de validité.',
      visaGrantedSaved: 'Visa accordé : informations enregistrées.',
      visaConfirmGranted: 'Confirmer Visa Accordé',
      visaReadyDocsModalTitle: 'Documents Prêts pour Dépôt -',
      visaProvidedDocsList: 'Liste des documents fournis :',
      visaConfirmReadyToSubmit: 'Confirmer Prêt pour Dépôt',
      visaReadyMarked: 'Dossier marqué comme "Prêt pour dépôt".',
      visaRefusedModalTitle: 'Visa Refusé - Dossier de',
      visaRefusedFinalWarning: 'Cette action est définitive. Le dossier sera clôturé.',
      visaConfirmRefusal: 'Confirmer le refus',
      visaRefusedClosed: 'Visa refusé : dossier clôturé.',
      visaUnauthorized401: 'Non autorisé (401). Merci de vous reconnecter.',
      visaMissingFileUrl: 'URL fichier manquante.',
      visaInvalidUrl: 'URL invalide.',
      visaMissingApiEnv: 'REACT_APP_API_URL manquant (.env)',
      visaLoadingEmployeesError: 'Erreur chargement employees',
      visaLoadingFilesError: 'Erreur chargement dossiers',
      visaOpenFileError: 'Erreur ouverture dossier',
      visaUpdateDocError: 'Erreur mise à jour document',
      visaUpdateFileError: 'Erreur mise à jour dossier',
      visaPdfUploading: 'Upload du PDF…',
      visaPdfUploadedSuccess: 'PDF uploadé avec succès.',
      visaUploadError: 'Erreur upload',
      visaGenerating: 'Génération…',
      visaGeneratedSuccess: 'Fichier généré avec succès.',
      visaGenerationError: 'Erreur génération',
      visaGenerationNotAvailable: 'Génération non disponible pour ce document.',
      visaSendingEmail: 'Envoi de l\'email…',
      visaEmailSent: 'Email envoyé ✅',
      visaEmailNotSent: 'Email non envoyé ❌ :',
      visaEmailNotAvailable: 'Envoi mail non disponible pour ce document.',
      visaEmployeeNotFoundInFile: 'Employé introuvable dans le dossier.',
      visaPdfUploaded: 'PDF uploadé avec succès.',
      visaNoEmployeeFound: 'Aucun employé trouvé',
      
      // Common
      yes: 'Oui',
      no: 'Non',
      na: 'N/A',
      optional: 'Optionnel',
      required: 'Obligatoire',
      success: 'Succès',
      warning: 'Avertissement',
      info: 'Information',
      confirm: 'Confirmer',
      delete: 'Supprimer',
      edit: 'Modifier',
      view: 'Voir',
      download: 'Télécharger',
      upload: 'Uploader',
      search: 'Rechercher',
      filter: 'Filtrer',
      sort: 'Trier',
      previous: 'Précédent',
      next: 'Suivant',
      first: 'Premier',
      last: 'Dernier',
      today: 'Aujourd\'hui',
      yesterday: 'Hier',
      thisWeek: 'Cette semaine',
      thisMonth: 'Ce mois',
      thisYear: 'Cette année',
      all: 'Tous',
      none: 'Aucun',
      unknown: 'Inconnu',
      notAvailable: 'Non disponible',
      notSpecified: 'Non spécifié',
      add: 'Ajouter',
      remove: 'Supprimer',
      update: 'Mettre à jour',
      create: 'Créer',
      back: 'Retour',
      nextStep: 'Étape suivante',
      finish: 'Terminer',
      export: 'Exporter',
      import: 'Importer',
      reset: 'Réinitialiser',
      apply: 'Appliquer',
      select: 'Sélectionner',
      choose: 'Choisir',
      browse: 'Parcourir',
      dragAndDrop: 'Glisser-déposer',
      or: 'ou',
      and: 'et',
      with: 'avec',
      without: 'sans',
      per: 'par',
      total: 'Total',
      average: 'Moyenne',
      minimum: 'Minimum',
      maximum: 'Maximum',
      median: 'Médiane',
      count: 'Nombre',
      percentage: 'Pourcentage',
      ratio: 'Ratio',
      date: 'Date',
      time: 'Heure',
      datetime: 'Date et heure',
      name: 'Nom',
      fullName: 'Nom complet',
      emailAddress: 'Adresse email',
      phone: 'Téléphone',
      address: 'Adresse',
      city: 'Ville',
      country: 'Pays',
      postCode: 'Code postal',
      description: 'Description',
      comments: 'Commentaires',
      notes: 'Notes',
      remarks: 'Remarques',
      attachment: 'Pièce jointe',
      file: 'Fichier',
      document: 'Document',
      image: 'Image',
      photo: 'Photo',
      video: 'Vidéo',
      audio: 'Audio',
      size: 'Taille',
      format: 'Format',
      extension: 'Extension',
      dimensions: 'Dimensions',
      resolution: 'Résolution',
      quality: 'Qualité',
      preferences: 'Préférences',
      configuration: 'Configuration',
      options: 'Options',
      advanced: 'Avancé',
      basic: 'Basique',
      simple: 'Simple',
      complex: 'Complexe',
      easy: 'Facile',
      difficult: 'Difficile',
      quick: 'Rapide',
      slow: 'Lent',
      fast: 'Vite',
      new: 'Nouveau',
      old: 'Ancien',
      recent: 'Récent',
      current: 'Actuel',
      future: 'Futur',
      past: 'Passé',
      present: 'Présent',
      active: 'Actif',
      inactive: 'Inactif',
      enabled: 'Activé',
      disabled: 'Désactivé',
      visible: 'Visible',
      hidden: 'Caché',
      public: 'Public',
      private: 'Privé',
      shared: 'Partagé',
      personal: 'Personnel',
      professional: 'Professionnel',
      business: 'Affaires',
      financialInfo: 'Informations financières',
      legalInfo: 'Informations légales',
      employee_ID: 'Matricule d\'employé',
      noEmployeesRegistered: 'Aucun employé enregistré',
      startByAddingFirstEmployee: 'Commencez par ajouter votre premier employé',
      exportSuccess: 'Exportation réussie',
      exportError: 'Erreur lors de l\'exportation',
      errorLoadingDashboard: 'Erreur lors du chargement du dashboard',
      loadingStats: 'Chargement des statistiques...',
      errorLoadingEmployees: 'Erreur lors du chargement des employés',
      errorLoadingEmployeesAlert: 'Erreur lors du chargement de la liste des employés',
      loadingEmployees: 'Chargement des employés...',
    },
    en: {
      // Navigation
      dashboard: 'Dashboard',
      team: 'Team',
      demands: 'HR Requests',
      payslip: 'Payslip',
      archives: 'Archives',
      statistics: 'Statistics',
      settings: 'Settings',
      visa: 'Visa Requests',
      logout: 'Logout',
      language: 'Language',
      
      // Header et titres
      appTitle: 'HR Manager',
      appSubtitle: 'Human Resources Management',
      lastUpdate: 'Last update',
      welcome: 'Welcome',
      overview: 'Overview',
      details: 'Details',
      actions: 'Actions',
      quickActions: 'Quick Actions',
      summary: 'Summary',
      
      // Dashboard
      totalEmployees: 'Total Employees',
      newThisMonth: 'New This Month',
      contractsToRenew: 'Contracts to Renew',
      totalSalary: 'Total Salary Mass',
      archivesCount: 'Archived Employees',
      manageTeam: 'Manage Team',
      advancedAnalytics: 'Advanced Analytics',
      viewStatistics: 'View Statistics',
      viewArchives: 'View Archives',
      exportData: 'Export Data',
      activeGrowth: 'Active growth',
      stableThisMonth: 'Stable this month',
      next30Days: 'In the next 30 days',
      monthlyGross: 'Monthly gross salary total',
      formerEmployees: 'Former employees',
      hrisThisMonth: 'Hires this month',
      activeEmployees: 'Active employees',
      hiresThisMonth: 'Hires this month',
      cdiContracts: 'CDI Contracts',
      cddContracts: 'CDD Contracts',
      civpContracts: 'CIVP Contracts',
      toRenew: 'To renew',
      salaryMass: 'Salary mass',
      archivedEmployees: 'Archived employees',
      downloadEmployeeList: 'Download employee list',
      excelFormat: 'Excel format',
      generating: 'Generating...',
      exporting: 'Exporting...',
      exportExcel: 'Export Excel',
      
      // Team
      employeeManagement: 'Team Management',
      consultEmployees: 'View and manage your active employees information',
      searchPlaceholder: 'Search by name, first name, position or employee ID...',
      employeesFound: 'employee(s) found',
      refresh: 'Refresh',
      addEmployee: 'Add Employee',
      noResults: 'No employee found',
      noResultsForSearch: 'No results for your search',
      noActiveEmployees: 'No active employees',
      addFirstEmployee: 'Add first employee',
      
      // Employee Modal
      employeeDetails: 'Employee Details',
      personalInfo: 'Personal Information',
      professionalInfo: 'Professional Information',
      emailContacts: 'Email Contacts',
      documents: 'Documents',
      editInfo: 'Edit Information',
      save: 'Save',
      cancel: 'Cancel',
      changePhoto: 'Change photo',
      departureDate: 'Departure date',
      archiveEmployee: 'Archive employee',
      archiveHint: 'Add a departure date to be able to archive the employee',
      addUpdateDossier: 'Add/Update HR dossier',
      noDocument: 'No document',
      requiredField: 'This field is required',
      optional: 'Optional',
      passportIssueDate: 'Passport Issue Date',
      passportExpiryDate: 'Passport Expiry Date',
      employeeID: 'Employee ID',
      lastName: 'Last name',
      firstName: 'First name',
      birthDate: 'Birth Date',
      identification: 'Identification',
      idNumber: 'ID Number',
      passport: 'Passport',
      position: 'Position',
      department: 'Site/Department',
      contractType: 'Contract Type',
      startDate: 'Start Date',
      grossSalary: 'Gross Salary',
      contactInfo: 'Contact Information',
      employeeEmail: 'Employee email',
      supervisor1Email: 'Supervisor 1 email',
      supervisor2Email: 'Supervisor 2 email',
      hireDate: 'Hire Date',
      contractEndDate: 'Contract End Date',
      daysRemaining: 'Days remaining',
      emailNotSpecified: 'Not specified',
      contractEndingSoon: 'Contract ending soon',
      endsOn: 'Ends on',
      since: 'Since',
      newPhotoSelected: 'New photo selected',
      hrFile: 'HR File',
      departureInterview: 'Departure Interview',
      interviewPDF: 'Interview PDF',
      deleteDossier: 'Delete dossier',
      confirmDeleteDossier: 'Confirm Dossier Deletion',
      confirmDeleteCheckbox: 'I confirm I want to delete this HR dossier',
      deleting: 'Deleting...',
      confirmDelete: 'Confirm Delete',
      changesSaved: 'Changes saved',
      saveError: 'Error saving changes',
      dossierDeletedSuccess: 'HR dossier deleted successfully',
      errorDeletingDossier: 'Error deleting dossier',
      confirmCheckboxRequired: 'Please check the confirmation box',
      notAuthenticated: 'Not authenticated',
      networkError: 'Network error',
      serverErrorContactAdmin: 'Server error, contact administrator',
      dateFormatError: 'Date format error',
      archiveError: 'Error archiving',
      employeeArchived: 'Employee archived successfully',
      addDepartureDateFirst: 'Add departure date first',
      notPDFConfirm: 'This link does not seem to be a PDF. Do you still want to open it?',
      select: 'Select',
      saving: 'Saving...',
      
      // Add Employee Modal
      addNewEmployee: 'Add New Employee',
      employeePhoto: 'Employee photo',
      clickToSelectPhoto: 'Click to select a photo',
      photoRequirements: 'JPG, PNG, GIF (max 5MB)',
      choosePhoto: 'Choose photo',
      removePhoto: 'Remove',
      createEmployee: 'Create Employee',
      uploadingPhoto: 'Uploading photo...',
      creating: 'Creating...',
      validEmployeeEmail: 'Please enter a valid employee email',
      validSupervisor1Email: 'Please enter a valid supervisor 1 email',
      validSupervisor2Email: 'Please enter a valid supervisor 2 email',
      fillRequiredFields: 'Please fill all required fields',
      photoUploadError: 'Error uploading photo',
      photoUploadErrorAlert: 'Unable to upload photo, using default avatar',
      employeeCreated: 'Employee created successfully',
      creationError: 'Error creating employee',
      selectImage: 'Please select an image',
      fileSizeExceeded: 'File is too large (max 5MB)',
      headquarters: 'Headquarters',
      uploadPhoto: 'Upload a photo',
      optionalForPermanent: 'Optional for permanent',
      
      // Départements
      Commerce: 'Commerce',
      Finance: 'Finance',
      Chiffrage: 'Chiffrage',
      Digitale: 'Digital',
      Général: 'General',
      'Logistique Germany': 'Logistics Germany',
      'Logistique Groupe': 'Group Logistics',
      Achat: 'Purchasing',
      Qualité: 'Quality',
      
      // Archive Modal
      archiveEmployeeTitle: 'Archive Employee',
      uploadDepartureInterview: 'Upload Departure Interview PDF',
      required: 'Required',
      attachReport: 'Attach departure interview report in PDF format',
      clickToSelectFile: 'Click to select a file',
      dragDropHere: 'or drag and drop your PDF file here',
      pdfOnly: 'PDF format only',
      uploading: 'Uploading',
      doNotClose: 'Do not close this window during upload...',
      uploadSuccess: 'PDF uploaded successfully!',
      previewPDF: 'Preview PDF',
      changeFile: 'Change file',
      confirmArchive: 'Archive employee',
      processing: 'Processing...',
      archiveNote: 'Archiving will take effect immediately after confirmation',
      
      // Archives Page
      archivedEmployees: 'Archived Employees',
      formerEmployeesList: 'List of employees who left the company',
      withInterview: 'With Interview',
      departureInterviews: 'Departure Interviews',
      searchArchives: 'Search in archives...',
      backToTeam: 'Back to team',
      noArchives: 'No archived employee',
      archivedWillAppear: 'Archived employees will appear here after their departure',
      viewActiveEmployees: 'View active employees',
      departure: 'Departure',
      viewInterview: 'View interview',
      archiveDetails: 'Archived Employee Details',
      archiveDocuments: 'Archive Documents',
      mainArchiveDocument: 'Main archive document',
      legacyFormat: 'Legacy format document',
      completeHRFile: 'Complete HR File',
      noDocumentsAvailable: 'No archive document available',
      archivedWithoutDocument: 'Employee was archived without departure interview document',
      archiveInfo: 'Archive Information',
      creationDate: 'Creation date',
      documentsKept: 'Archive documents are kept for a minimum of 5 years',
      printDetails: 'Print',
      backToList: 'Back to list',
      errorLoadingArchives: 'Error loading archives',
      errorLoadingArchivesAlert: 'Error loading archived employees',
      noDepartureInterviewAvailable: 'No departure interview available',
      invalidInterviewLink: 'Invalid interview link',
      errorOpeningPDF: 'Error opening PDF',
      loadingArchives: 'Loading archives...',
      totalArchived: 'Total archived',
      
      // ArchiveEmployeeModal
      career: 'Career',
      documentStoredOnServer: 'Document stored on server',
      externalLink: 'External link',
      pdfOpenError: 'PDF opening error',
      cannotOpenDocument: 'Cannot open document. Link may be invalid.',
      noHRDossierAvailable: 'No HR dossier available',
      invalidURL: 'Link is not a valid URL',
      link: 'Link',
      opening: 'Opening',
      openPDF: 'Open PDF',
      legacy: 'legacy',
      openLink: 'Open link',
      hrDossier: 'HR dossier',
      consultDossier: 'Consult dossier',
      days: 'days',
      url: 'URL',
      status: 'Status',
      archived: 'Archived',
      close: 'Close',
      print: 'Print',
      
      // Statistics
      statisticsDashboard: 'Statistics Dashboard',
      hrAnalysis: 'Detailed analysis of your human resources',
      departmentDistribution: 'Department Distribution',
      contractTypes: 'Contract Types',
      salaryAnalysis: 'Salary Analysis',
      recentHires: 'Recent Hires',
      minimumSalary: 'Minimum Salary',
      maximumSalary: 'Maximum Salary',
      medianSalary: 'Median Salary',
      averageSalary: 'Average Salary',
      exportDataPDF: 'Export to PDF',
      exportStatisticsExcel: 'Export Statistics Excel',
      exportEmployeesExcel: 'Export Employees Excel',
      noHiresThisMonth: 'No hires this month',
      errorLoadingStats: 'Error loading statistics',
      loadingStatistics: 'Loading statistics...',
      departments: 'Departments',
      activeSites: 'Active sites',
      perEmployee: 'Per employee',
      detailedStats: 'Detailed statistics',
      viewTrends: 'View trends',
      
      // Demandes RH
      hrRequests: 'HR Requests Consultation',
      requestTracking: 'Visualization and tracking of employee requests',
      searchFilters: 'Search filters',
      allStatus: 'All status',
      allTypes: 'All types',
      allDates: 'All dates',
      fromDate: 'From date',
      toDate: 'To date',
      activeFilters: 'Active filters',
      clearFilters: 'Clear filters',
      exportExcel: 'Export Excel',
      totalRequests: 'Total requests',
      pending: 'Pending',
      approved: 'Approved',
      refused: 'Refused',
      results: 'Results',
      page: 'Page',
      of: 'of',
      noRequests: 'No request found',
      noMatchingCriteria: 'No request matches your search criteria',
      showAllRequests: 'Show all requests',
      leaveType: 'Leave type',
      approvalProcess: 'Approval process',
      createdOn: 'Created on',
      lastUpdated: 'Last updated',
      refusalComment: 'Refusal comment',
      viewDetails: 'View full details',
      generalInfo: 'General information',
      employeeInfo: 'Employee information',
      requestDetails: 'Request details',
      startDateReq: 'Start date',
      returnDate: 'Return date',
      departureTime: 'Departure time',
      returnTime: 'Return time',
      travelExpenses: 'Travel expenses',
      halfDay: 'Half day',
      supervisor1: 'Supervisor 1',
      supervisor2: 'Supervisor 2',
      notAssigned: 'Not assigned',
      notRequired: 'Not applicable',
      missingAuthToken: 'Missing authentication token',
      serverError: 'Server error',
      errorFetchingRequests: 'Error fetching requests',
      connectionError: 'Connection error',
      loadingRequests: 'Loading requests...',
      applyingFilters: 'Applying filters...',
      loadingError: 'Loading error',
      noRequestsAvailable: 'No requests available',
      email: 'Email',
      title: 'Title',
      type: 'Type',
      employee: 'Employee',
      na: 'N/A',
      emailNotAvailable: 'Email not available',
      yes: 'Yes',
      justNow: 'Just now',
      minutesAgo: 'min',
      hoursAgo: 'h',
      noNewNotifications: 'No new notifications',
      notifications: 'Notifications',
      loading: 'Loading...',
      viewAll: 'View all requests',
      
      // Fiche de Paie
      payslip: 'Payslip',
      autoSendPayslips: 'Automatic sending of payslips to employees',
      importPDF: 'Import PDF file',
      pdfDescription: 'PDF must contain one payslip per page. Each slip must have the employee ID (MATR.).',
      choosePDF: 'Choose PDF file',
      processAndSend: 'Process and send',
      processingInProgress: 'Processing in progress...',
      extractingMatricules: 'Extracting IDs and sending emails...',
      mayTakeSeveralMinutes: 'This may take several minutes depending on number of pages',
      processingComplete: 'Processing complete',
      sheetsSent: 'sheet(s) sent out of',
      pages: 'page(s)',
      errorDetails: 'Error details',
      employeeMatricule: 'Employee ID',
      error: 'Error',
      invalidPDF: 'Please select a valid PDF file',
      selectPDF: 'Please select a PDF file',
      processingError: 'Processing error',
      uploadError: 'Upload error',
      fileProcessingError: 'File processing error',
      
      // Login
      login: 'Login',
      loginToYourAccount: 'Log in to your account',
      password: 'Password',
      forgotPassword: 'Forgot password?',
      resetPassword: 'Reset password',
      enterEmailForNewPassword: 'Enter your email address to receive a new password.',
      sendNewPassword: 'Send new password',
      backToLogin: 'Back to login',
      temporaryPasswordNote: 'An email with a new password will be sent to you. This password is temporary, change it after login. Check your spam if you don\'t receive the email.',
      appDescription: 'Human resources management application',
      version: 'Version',
      emailPasswordIncorrect: 'Email or password incorrect',
      loggingIn: 'Logging in...',
      sending: 'Sending...',
      yourPassword: 'Your password',
      
      // Settings
      settings: 'Settings',
      managePreferences: 'Manage your application preferences and settings',
      chooseLanguage: 'Choose application display language',
      currentLanguage: 'Current language',
      changeEffectiveImmediately: 'Change takes effect immediately throughout the application',
      notifications: 'Notifications',
      configureNotifications: 'Configure how you receive notifications',
      emailNotifications: 'Email notifications',
      receiveAlertsByEmail: 'Receive important alerts by email',
      pushNotifications: 'Push notifications',
      realTimeAlerts: 'Real-time alerts in the application',
      weeklyReport: 'Weekly report',
      weeklySummaryEmail: 'Receive weekly summary by email',
      about: 'About',
      userGuide: 'User guide',
      technicalSupport: 'Technical support',
      termsOfUse: 'Terms of use',
      privacyPolicy: 'Privacy policy',
      saveChanges: 'Save changes',
      restoreDefaults: 'Restore defaults',
      languageChangedTo: 'Language changed to',
      defaultLanguage: 'Default language',
      englishLanguage: 'English language',
      chineseLanguage: 'Chinese language',
      
      // Visa
      visaTitle: 'France Visa Files',
      visaSubtitleDashboard: 'Business visa requests management - Dashboard',
      visaSubtitleDetail: 'Detailed visa file tracking',
      visaBackToDashboard: 'Back to dashboard',
      visaStepsDocsValidated: 'Validated documents',
      visaStepsReadyToSubmit: 'Ready to submit',
      visaStepsResult: 'Visa result',
      docStatusMissing: 'Missing',
      docStatusUploaded: 'Uploaded',
      docStatusRejected: 'Rejected',
      docStatusReceivedPhysical: 'Received physically',
      visaDocTypeBring: 'To bring',
      visaDocTypeSpecificEmail: 'Specific email',
      visaDocTypeBooking: 'Booking.com',
      visaDocTypeFranceVisas: 'France-Visas',
      visaDocTypePdfGeneration: 'PDF generation',
      visaDocTypeUploadPdf: 'Upload PDF',
      visaOneFile: 'file',
      visaManyFiles: 'files',
      visaEmployee: 'Employee',
      visaStatus: 'Status',
      visaReason: 'Reason',
      visaDeparture: 'Departure',
      visaReturn: 'Return',
      visaProgress: 'Progress',
      visaVisaNumberShort: 'Visa No.',
      visaValidity: 'Validity',
      visaActions: 'Actions',
      visaConsult: 'View',
      visaNoFileInList: 'No file in this list',
      visaCreateNewToStart: 'Create a new file to get started',
      visaSearchPlaceholder: 'Search an employee or a reason...',
      visaFilterStatus: 'Status',
      visaOneFileFound: 'file found',
      visaFilesFound: 'files found',
      visaSectionInProgress: '📋 In-progress files',
      visaSectionReadyToSubmit: '✅ Files ready to submit',
      visaSectionGranted: '🎉 Visa granted',
      visaSectionRefused: '❌ Visa refused',
      visaStatusInProgress: 'In progress',
      visaStatusReadyToSubmit: 'Ready to submit',
      visaStatusGranted: 'Visa granted',
      visaStatusRefused: 'Visa refused',
      visaKpiInProgress: 'In-progress files',
      visaKpiReadyToSubmit: 'Ready to submit',
      visaKpiGranted: 'Visa granted',
      visaKpiRefused: 'Visa refused',
      visaNewFile: 'New file',
      visaCreateNewFile: 'Create a new visa file',
      visaFullName: 'Last name & First name',
      visaEmployeesGroupLabel: 'Employees - STS',
      visaCreateFile: 'Create file',
      visaCancel: 'Cancel',
      visaEmployeeGeneric: 'Employee',
      visaFillAllRequired: 'Please fill in all required fields.',
      visaReturnDateAfterDeparture: 'Return date must be >= departure date.',
      visaCreateFileLoading: 'Creating file...',
      visaFileCreatedEmailSent: 'File created. Email sent to',
      visaFileCreatedEmailNotSent: 'File created, but email NOT sent to',
      visaCreateError: 'File creation error',
      visaLoadingFiles: 'Loading visa files...',
      visaFileSummary: 'File summary',
      visaTripReason: 'Trip reason',
      visaFileStatus: 'File status',
      visaDocsProvidedPct: '% of required documents are provided',
      visaDocsProvidedCountLine: 'required documents provided',
      visaMissingDocs: 'missing',
      visaPhysicalToBring: 'to bring physically',
      visaReadyToSubmitBtn: 'Ready to submit',
      visaDecisionTitle: 'Visa decision',
      visaGrantedBtn: 'Visa granted',
      visaRefusedBtn: 'Visa refused',
      visaResultLockedHint: 'Visa result is available after "Ready to submit".',
      visaFileClosedHint: 'File closed: final result locked.',
      visaFileClosed: 'File closed',
      visaFileDocs: 'File documents',
      visaDoc: 'Document',
      visaType: 'Type',
      visaSendEmailBtn: 'Send email',
      visaUploadPdfBtn: 'Upload PDF',
      visaPreviewBtn: 'Preview',
      visaFillFormBtn: 'Fill form',
      visaUploadReceiptBtn: 'Upload receipt',
      visaPreviewPdfBtn: 'Preview PDF',
      visaBookHotelBtn: 'Book hotel',
      visaGeneratePdfBtn: 'Generate PDF',
      visaReceivedBtn: 'Received',
      visaAllDocsRequiredBeforeReady: 'All required documents must be provided before marking ready to submit.',
      docMarkedReceivedPhysical: 'Document marked as received physically.',
      visaMissingPdf: 'No PDF uploaded.',
      visaMissingReceiptPdf: 'No receipt PDF uploaded.',
      visaMissingBookingPdf: 'No booking PDF uploaded.',
      visaNoGeneratedFile: 'No generated file.',
      visaOpenPdfToPrint: 'Opening PDF for printing...',
      visaPrintPdfError: 'PDF print error',
      visaPrintDocs: '🖨 Print documents',
      visaFillVisaNumberAndDates: 'Please fill visa number + validity dates.',
      visaGrantedSaved: 'Visa granted: information saved.',
      visaConfirmGranted: 'Confirm visa granted',
      visaReadyDocsModalTitle: 'Documents Ready to Submit -',
      visaProvidedDocsList: 'Provided documents list:',
      visaConfirmReadyToSubmit: 'Confirm ready to submit',
      visaReadyMarked: 'File marked as "Ready to submit".',
      visaRefusedModalTitle: 'Visa Refused - File of',
      visaRefusedFinalWarning: 'This action is final. The file will be closed.',
      visaConfirmRefusal: 'Confirm refusal',
      visaRefusedClosed: 'Visa refused: file closed.',
      visaUnauthorized401: 'Unauthorized (401). Please log in again.',
      visaMissingFileUrl: 'Missing file URL.',
      visaInvalidUrl: 'Invalid URL.',
      visaMissingApiEnv: 'Missing REACT_APP_API_URL (.env)',
      visaLoadingEmployeesError: 'Error loading employees',
      visaLoadingFilesError: 'Error loading files',
      visaOpenFileError: 'Error opening file',
      visaUpdateDocError: 'Error updating document',
      visaUpdateFileError: 'Error updating file',
      visaPdfUploading: 'Uploading PDF...',
      visaPdfUploadedSuccess: 'PDF uploaded successfully.',
      visaUploadError: 'Upload error',
      visaGenerating: 'Generating...',
      visaGeneratedSuccess: 'File generated successfully.',
      visaGenerationError: 'Generation error',
      visaGenerationNotAvailable: 'Generation not available for this document.',
      visaSendingEmail: 'Sending email...',
      visaEmailSent: 'Email sent ✅',
      visaEmailNotSent: 'Email not sent ❌ :',
      visaEmailNotAvailable: 'Email sending not available for this document.',
      visaEmployeeNotFoundInFile: 'Employee not found in file.',
      visaPdfUploaded: 'PDF uploaded successfully.',
      visaNoEmployeeFound: 'No employee found',
      
      // Common
      yes: 'Yes',
      no: 'No',
      na: 'N/A',
      optional: 'Optional',
      required: 'Required',
      success: 'Success',
      warning: 'Warning',
      info: 'Information',
      confirm: 'Confirm',
      delete: 'Delete',
      edit: 'Edit',
      view: 'View',
      download: 'Download',
      upload: 'Upload',
      search: 'Search',
      filter: 'Filter',
      sort: 'Sort',
      previous: 'Previous',
      next: 'Next',
      first: 'First',
      last: 'Last',
      today: 'Today',
      yesterday: 'Yesterday',
      thisWeek: 'This week',
      thisMonth: 'This month',
      thisYear: 'This year',
      all: 'All',
      none: 'None',
      unknown: 'Unknown',
      notAvailable: 'Not available',
      notSpecified: 'Not specified',
      add: 'Add',
      remove: 'Remove',
      update: 'Update',
      create: 'Create',
      back: 'Back',
      nextStep: 'Next step',
      finish: 'Finish',
      export: 'Export',
      import: 'Import',
      reset: 'Reset',
      apply: 'Apply',
      select: 'Select',
      choose: 'Choose',
      browse: 'Browse',
      dragAndDrop: 'Drag and drop',
      or: 'or',
      and: 'and',
      with: 'with',
      without: 'without',
      per: 'per',
      total: 'Total',
      average: 'Average',
      minimum: 'Minimum',
      maximum: 'Maximum',
      median: 'Median',
      count: 'Count',
      percentage: 'Percentage',
      ratio: 'Ratio',
      date: 'Date',
      time: 'Time',
      datetime: 'Date and time',
      name: 'Name',
      fullName: 'Full name',
      emailAddress: 'Email address',
      phone: 'Phone',
      address: 'Address',
      city: 'City',
      country: 'Country',
      postCode: 'Postal code',
      description: 'Description',
      comments: 'Comments',
      notes: 'Notes',
      remarks: 'Remarks',
      attachment: 'Attachment',
      file: 'File',
      document: 'Document',
      image: 'Image',
      photo: 'Photo',
      video: 'Video',
      audio: 'Audio',
      size: 'Size',
      format: 'Format',
      extension: 'Extension',
      dimensions: 'Dimensions',
      resolution: 'Resolution',
      quality: 'Quality',
      preferences: 'Preferences',
      configuration: 'Configuration',
      options: 'Options',
      advanced: 'Advanced',
      basic: 'Basic',
      simple: 'Simple',
      complex: 'Complex',
      easy: 'Easy',
      difficult: 'Difficult',
      quick: 'Quick',
      slow: 'Slow',
      fast: 'Fast',
      new: 'New',
      old: 'Old',
      recent: 'Recent',
      current: 'Current',
      future: 'Future',
      past: 'Past',
      present: 'Present',
      active: 'Active',
      inactive: 'Inactive',
      enabled: 'Enabled',
      disabled: 'Disabled',
      visible: 'Visible',
      hidden: 'Hidden',
      public: 'Public',
      private: 'Private',
      shared: 'Shared',
      personal: 'Personal',
      professional: 'Professional',
      business: 'Business',
      financialInfo: 'Financial information',
      legalInfo: 'Legal information',
      employee_ID: 'Employee ID',
      noEmployeesRegistered: 'No employees registered',
      startByAddingFirstEmployee: 'Start by adding your first employee',
      exportSuccess: 'Export successful',
      exportError: 'Error during export',
      errorLoadingDashboard: 'Error loading dashboard',
      loadingStats: 'Loading statistics...',
      errorLoadingEmployees: 'Error loading employees',
      errorLoadingEmployeesAlert: 'Error loading employee list',
      loadingEmployees: 'Loading employees...',
    },
    zh: {
      // Navigation
      dashboard: '仪表板',
      team: '团队',
      demands: '人力资源请求',
      payslip: '工资单',
      archives: '档案',
      statistics: '统计',
      settings: '设置',
      visa: '签证请求',
      logout: '登出',
      language: '语言',
      
      // Header et titres
      appTitle: '人力资源经理',
      appSubtitle: '人力资源管理',
      lastUpdate: '最后更新',
      welcome: '欢迎',
      overview: '概览',
      details: '详情',
      actions: '操作',
      quickActions: '快速操作',
      summary: '摘要',
      
      // Dashboard
      totalEmployees: '员工总数',
      newThisMonth: '本月新增',
      contractsToRenew: '待续约合同',
      totalSalary: '薪资总额',
      archivesCount: '归档员工',
      manageTeam: '管理团队',
      advancedAnalytics: '高级分析',
      viewStatistics: '查看统计',
      viewArchives: '查看档案',
      exportData: '导出数据',
      activeGrowth: '活跃增长',
      stableThisMonth: '本月稳定',
      next30Days: '未来30天内',
      monthlyGross: '月度总薪资',
      formerEmployees: '前员工',
      hrisThisMonth: '本月招聘',
      activeEmployees: '活跃员工',
      hiresThisMonth: '本月招聘',
      cdiContracts: 'CDI合同',
      cddContracts: 'CDD合同',
      civpContracts: 'CIVP合同',
      toRenew: '待续约',
      salaryMass: '薪资总额',
      archivedEmployees: '归档员工',
      downloadEmployeeList: '下载员工列表',
      excelFormat: 'Excel格式',
      generating: '生成中...',
      exporting: '导出中...',
      exportExcel: '导出Excel',
      
      // Team
      employeeManagement: '团队管理',
      consultEmployees: '查看和管理您的在职员工信息',
      searchPlaceholder: '按姓名、职位或员工ID搜索...',
      employeesFound: '名员工找到',
      refresh: '刷新',
      addEmployee: '添加员工',
      noResults: '未找到员工',
      noResultsForSearch: '搜索无结果',
      noActiveEmployees: '无活跃员工',
      addFirstEmployee: '添加第一名员工',
      
      // Employee Modal
      employeeDetails: '员工详情',
      personalInfo: '个人信息',
      professionalInfo: '职业信息',
      emailContacts: '电子邮件联系人',
      documents: '文件',
      editInfo: '编辑信息',
      save: '保存',
      cancel: '取消',
      changePhoto: '更换照片',
      departureDate: '离职日期',
      archiveEmployee: '归档员工',
      archiveHint: '添加离职日期以归档员工',
      addUpdateDossier: '添加/更新人力资源档案',
      noDocument: '无文件',
      requiredField: '此字段为必填项',
      optional: '可选',
      passportIssueDate: '护照签发日期',
      passportExpiryDate: '护照到期日期',
      employeeID: '员工ID',
      lastName: '姓氏',
      firstName: '名字',
      birthDate: '出生日期',
      identification: '身份信息',
      idNumber: '身份证号',
      passport: '护照',
      position: '职位',
      department: '地点/部门',
      contractType: '合同类型',
      startDate: '开始日期',
      grossSalary: '基本工资',
      contactInfo: '联系信息',
      employeeEmail: '员工邮箱',
      supervisor1Email: '主管1邮箱',
      supervisor2Email: '主管2邮箱',
      hireDate: '雇佣日期',
      contractEndDate: '合同结束日期',
      daysRemaining: '剩余天数',
      emailNotSpecified: '未指定',
      contractEndingSoon: '合同即将结束',
      endsOn: '结束于',
      since: '自',
      newPhotoSelected: '已选择新照片',
      hrFile: '人力资源档案',
      departureInterview: '离职面谈',
      interviewPDF: '面谈PDF',
      deleteDossier: '删除档案',
      confirmDeleteDossier: '确认删除档案',
      confirmDeleteCheckbox: '我确认要删除此人力资源档案',
      deleting: '删除中...',
      confirmDelete: '确认删除',
      changesSaved: '更改已保存',
      saveError: '保存错误',
      dossierDeletedSuccess: '人力资源档案删除成功',
      errorDeletingDossier: '删除档案时出错',
      confirmCheckboxRequired: '请勾选确认框',
      notAuthenticated: '未认证',
      networkError: '网络错误',
      serverErrorContactAdmin: '服务器错误，请联系管理员',
      dateFormatError: '日期格式错误',
      archiveError: '归档错误',
      employeeArchived: '员工归档成功',
      addDepartureDateFirst: '请先添加离职日期',
      notPDFConfirm: '此链接似乎不是PDF文件。是否仍要打开？',
      select: '选择',
      saving: '保存中...',
      
      // Add Employee Modal
      addNewEmployee: '添加新员工',
      employeePhoto: '员工照片',
      clickToSelectPhoto: '点击选择照片',
      photoRequirements: 'JPG、PNG、GIF格式（最大5MB）',
      choosePhoto: '选择照片',
      removePhoto: '删除',
      createEmployee: '创建员工',
      uploadingPhoto: '上传照片中...',
      creating: '创建中...',
      validEmployeeEmail: '请输入有效的员工邮箱',
      validSupervisor1Email: '请输入有效的主管1邮箱',
      validSupervisor2Email: '请输入有效的主管2邮箱',
      fillRequiredFields: '请填写所有必填字段',
      photoUploadError: '上传照片错误',
      photoUploadErrorAlert: '无法上传照片，使用默认头像',
      employeeCreated: '员工创建成功',
      creationError: '创建员工错误',
      selectImage: '请选择图片',
      fileSizeExceeded: '文件太大（最大5MB）',
      headquarters: '总部',
      uploadPhoto: '上传照片',
      optionalForPermanent: '永久合同可选',
      
      // Départements
      Commerce: '商业',
      Finance: '财务',
      Chiffrage: '估价',
      Digitale: '数字',
      Général: '总务',
      'Logistique Germany': '德国物流',
      'Logistique Groupe': '集团物流',
      Achat: '采购',
      Qualité: '质量',
      
      // Archive Modal
      archiveEmployeeTitle: '归档员工',
      uploadDepartureInterview: '上传离职面谈PDF',
      required: '必需',
      attachReport: '附上PDF格式的离职面谈报告',
      clickToSelectFile: '点击选择文件',
      dragDropHere: '或将PDF文件拖放到此处',
      pdfOnly: '仅限PDF格式',
      uploading: '上传中',
      doNotClose: '上传期间请勿关闭窗口...',
      uploadSuccess: 'PDF上传成功！',
      previewPDF: '预览PDF',
      changeFile: '更换文件',
      confirmArchive: '归档员工',
      processing: '处理中...',
      archiveNote: '确认后归档将立即生效',
      
      // Archives Page
      archivedEmployees: '已归档员工',
      formerEmployeesList: '已离职员工列表',
      withInterview: '有面谈记录',
      departureInterviews: '离职面谈',
      searchArchives: '在档案中搜索...',
      backToTeam: '返回团队',
      noArchives: '无归档员工',
      archivedWillAppear: '员工离职后将在此处显示',
      viewActiveEmployees: '查看在职员工',
      departure: '离职',
      viewInterview: '查看面谈',
      archiveDetails: '归档员工详情',
      archiveDocuments: '归档文件',
      mainArchiveDocument: '主要归档文件',
      legacyFormat: '旧格式文件',
      completeHRFile: '完整人力资源文件',
      noDocumentsAvailable: '无归档文件可用',
      archivedWithoutDocument: '员工归档时无离职面谈文件',
      archiveInfo: '归档信息',
      creationDate: '创建日期',
      documentsKept: '归档文件至少保存5年',
      printDetails: '打印',
      backToList: '返回列表',
      errorLoadingArchives: '加载档案错误',
      errorLoadingArchivesAlert: '加载归档员工错误',
      noDepartureInterviewAvailable: '无离职面谈可用',
      invalidInterviewLink: '面谈链接无效',
      errorOpeningPDF: '打开PDF错误',
      loadingArchives: '加载档案中...',
      totalArchived: '总计归档',
      
      // ArchiveEmployeeModal
      career: '职业生涯',
      documentStoredOnServer: '文档存储在服务器上',
      externalLink: '外部链接',
      pdfOpenError: 'PDF打开错误',
      cannotOpenDocument: '无法打开文档。链接可能无效。',
      noHRDossierAvailable: '无人力资源档案可用',
      invalidURL: '链接不是有效的URL',
      link: '链接',
      opening: '打开中',
      openPDF: '打开PDF',
      legacy: '旧版',
      openLink: '打开链接',
      hrDossier: '人力资源档案',
      consultDossier: '查阅档案',
      days: '天',
      url: '网址',
      status: '状态',
      archived: '已归档',
      close: '关闭',
      print: '打印',
      
      // Statistics
      statisticsDashboard: '统计仪表板',
      hrAnalysis: '人力资源详细分析',
      departmentDistribution: '部门分布',
      contractTypes: '合同类型',
      salaryAnalysis: '薪资分析',
      recentHires: '近期招聘',
      minimumSalary: '最低薪资',
      maximumSalary: '最高薪资',
      medianSalary: '中位薪资',
      averageSalary: '平均薪资',
      exportDataPDF: '导出为PDF',
      exportStatisticsExcel: '导出统计Excel',
      exportEmployeesExcel: '导出员工Excel',
      noHiresThisMonth: '本月无招聘',
      errorLoadingStats: '加载统计错误',
      loadingStatistics: '加载统计中...',
      departments: '部门',
      activeSites: '活跃站点',
      perEmployee: '每位员工',
      detailedStats: '详细统计',
      viewTrends: '查看趋势',
      
      // Demandes RH
      hrRequests: '人力资源请求咨询',
      requestTracking: '员工请求的查看和跟踪',
      searchFilters: '搜索过滤器',
      allStatus: '所有状态',
      allTypes: '所有类型',
      allDates: '所有日期',
      fromDate: '从日期',
      toDate: '至日期',
      activeFilters: '活动过滤器',
      clearFilters: '清除过滤器',
      exportExcel: '导出Excel',
      totalRequests: '总请求数',
      pending: '待处理',
      approved: '已批准',
      refused: '已拒绝',
      results: '结果',
      page: '页',
      of: '共',
      noRequests: '未找到请求',
      noMatchingCriteria: '无请求符合您的搜索条件',
      showAllRequests: '显示所有请求',
      leaveType: '请假类型',
      approvalProcess: '审批流程',
      createdOn: '创建于',
      lastUpdated: '最后更新',
      refusalComment: '拒绝评论',
      viewDetails: '查看完整详情',
      generalInfo: '一般信息',
      employeeInfo: '员工信息',
      requestDetails: '请求详情',
      startDateReq: '开始日期',
      returnDate: '返回日期',
      departureTime: '出发时间',
      returnTime: '返回时间',
      travelExpenses: '差旅费',
      halfDay: '半天',
      supervisor1: '主管1',
      supervisor2: '主管2',
      notAssigned: '未分配',
      notRequired: '不适用',
      missingAuthToken: '缺少认证令牌',
      serverError: '服务器错误',
      errorFetchingRequests: '获取请求错误',
      connectionError: '连接错误',
      loadingRequests: '加载请求中...',
      applyingFilters: '应用过滤器中...',
      loadingError: '加载错误',
      noRequestsAvailable: '无可用请求',
      email: '电子邮件',
      title: '标题',
      type: '类型',
      employee: '员工',
      na: '不适用',
      emailNotAvailable: '邮箱不可用',
      yes: '是',
      justNow: '刚刚',
      minutesAgo: '分钟前',
      hoursAgo: '小时前',
      noNewNotifications: '无新通知',
      notifications: '通知',
      loading: '加载中...',
      viewAll: '查看所有请求',
      
      // Fiche de Paie
      payslip: '工资单',
      autoSendPayslips: '自动向员工发送工资单',
      importPDF: '导入PDF文件',
      pdfDescription: 'PDF每页必须包含一张工资单。每张工资单必须有员工ID（MATR.）。',
      choosePDF: '选择PDF文件',
      processAndSend: '处理并发送',
      processingInProgress: '处理进行中...',
      extractingMatricules: '提取ID并发送电子邮件...',
      mayTakeSeveralMinutes: '根据页数可能需要几分钟',
      processingComplete: '处理完成',
      sheetsSent: '张工资单已发送，共',
      pages: '页',
      errorDetails: '错误详情',
      employeeMatricule: '员工ID',
      error: '错误',
      invalidPDF: '请选择有效的PDF文件',
      selectPDF: '请选择PDF文件',
      processingError: '处理错误',
      uploadError: '上传错误',
      fileProcessingError: '文件处理错误',
      
      // Login
      login: '登录',
      loginToYourAccount: '登录您的账户',
      password: '密码',
      forgotPassword: '忘记密码？',
      resetPassword: '重置密码',
      enterEmailForNewPassword: '输入您的电子邮件地址以接收新密码。',
      sendNewPassword: '发送新密码',
      backToLogin: '返回登录',
      temporaryPasswordNote: '将向您发送包含新密码的电子邮件。此密码为临时密码，登录后请更改。如果未收到电子邮件，请检查垃圾邮件。',
      appDescription: '人力资源管理应用',
      version: '版本',
      emailPasswordIncorrect: '邮箱或密码不正确',
      loggingIn: '登录中...',
      sending: '发送中...',
      yourPassword: '您的密码',
      
      // Settings
      settings: '设置',
      managePreferences: '管理您的应用偏好和设置',
      chooseLanguage: '选择应用显示语言',
      currentLanguage: '当前语言',
      changeEffectiveImmediately: '更改将在整个应用中立即生效',
      notifications: '通知',
      configureNotifications: '配置您接收通知的方式',
      emailNotifications: '电子邮件通知',
      receiveAlertsByEmail: '通过电子邮件接收重要警报',
      pushNotifications: '推送通知',
      realTimeAlerts: '应用中的实时警报',
      weeklyReport: '周报',
      weeklySummaryEmail: '通过电子邮件接收周报',
      about: '关于',
      userGuide: '用户指南',
      technicalSupport: '技术支持',
      termsOfUse: '使用条款',
      privacyPolicy: '隐私政策',
      saveChanges: '保存更改',
      restoreDefaults: '恢复默认值',
      languageChangedTo: '语言已更改为',
      defaultLanguage: '默认语言',
      englishLanguage: '英语',
      chineseLanguage: '中文',
      
      // Visa
      visaTitle: '法国签证档案',
      visaSubtitleDashboard: '商务签证申请管理 - 仪表板',
      visaSubtitleDetail: '签证档案详细跟踪',
      visaBackToDashboard: '返回仪表板',
      visaStepsDocsValidated: '文件已验证',
      visaStepsReadyToSubmit: '可提交',
      visaStepsResult: '签证结果',
      docStatusMissing: '缺失',
      docStatusUploaded: '已上传',
      docStatusRejected: '已拒绝',
      docStatusReceivedPhysical: '已收到（纸质）',
      visaDocTypeBring: '需携带',
      visaDocTypeSpecificEmail: '指定邮件',
      visaDocTypeBooking: 'Booking.com',
      visaDocTypeFranceVisas: 'France-Visas',
      visaDocTypePdfGeneration: '生成 PDF',
      visaDocTypeUploadPdf: '上传 PDF',
      visaOneFile: '档案',
      visaManyFiles: '档案',
      visaEmployee: '员工',
      visaStatus: '状态',
      visaReason: '原因',
      visaDeparture: '出发',
      visaReturn: '返回',
      visaProgress: '进度',
      visaVisaNumberShort: '签证号',
      visaValidity: '有效期',
      visaActions: '操作',
      visaConsult: '查看',
      visaNoFileInList: '此列表暂无档案',
      visaCreateNewToStart: '创建新档案以开始',
      visaSearchPlaceholder: '搜索员工或原因...',
      visaFilterStatus: '状态',
      visaOneFileFound: '找到档案',
      visaFilesFound: '找到档案',
      visaSectionInProgress: '📋 处理中档案',
      visaSectionReadyToSubmit: '✅ 可提交档案',
      visaSectionGranted: '🎉 签证已批准',
      visaSectionRefused: '❌ 签证被拒',
      visaStatusInProgress: '处理中',
      visaStatusReadyToSubmit: '可提交',
      visaStatusGranted: '签证已批准',
      visaStatusRefused: '签证被拒',
      visaKpiInProgress: '处理中档案',
      visaKpiReadyToSubmit: '可提交',
      visaKpiGranted: '已批准',
      visaKpiRefused: '已拒绝',
      visaNewFile: '新档案',
      visaCreateNewFile: '创建新的签证档案',
      visaFullName: '姓名',
      visaEmployeesGroupLabel: 'Employees - STS',
      visaCreateFile: '创建档案',
      visaCancel: '取消',
      visaEmployeeGeneric: '员工',
      visaFillAllRequired: '请填写所有必填字段。',
      visaReturnDateAfterDeparture: '返回日期必须 >= 出发日期。',
      visaCreateFileLoading: '正在创建档案…',
      visaFileCreatedEmailSent: '档案已创建，邮件已发送给',
      visaFileCreatedEmailNotSent: '档案已创建，但邮件未发送给',
      visaCreateError: '创建档案出错',
      visaLoadingFiles: '正在加载签证档案…',
      visaFileSummary: '档案摘要',
      visaTripReason: '出行原因',
      visaFileStatus: '档案状态',
      visaDocsProvidedPct: '％所需文件已提供',
      visaDocsProvidedCountLine: '所需文件已提供',
      visaMissingDocs: '缺失',
      visaPhysicalToBring: '需携带纸质',
      visaReadyToSubmitBtn: '可提交',
      visaDecisionTitle: '签证决定',
      visaGrantedBtn: '签证批准',
      visaRefusedBtn: '签证拒绝',
      visaResultLockedHint: '签证结果在"可提交"之后可用。',
      visaFileClosedHint: '档案已关闭：最终结果已锁定。',
      visaFileClosed: '档案已关闭',
      visaFileDocs: '档案文件',
      visaDoc: '文件',
      visaType: '类型',
      visaSendEmailBtn: '发送邮件',
      visaUploadPdfBtn: '上传 PDF',
      visaPreviewBtn: '预览',
      visaFillFormBtn: '填写表格',
      visaUploadReceiptBtn: '上传收据',
      visaPreviewPdfBtn: '预览 PDF',
      visaBookHotelBtn: '预订酒店',
      visaGeneratePdfBtn: '生成 PDF',
      visaReceivedBtn: '已接收',
      visaAllDocsRequiredBeforeReady: '标记为可提交前，必须提供所有必需文件。',
      docMarkedReceivedPhysical: '文件已标记为已收到（纸质）。',
      visaMissingPdf: '未上传 PDF。',
      visaMissingReceiptPdf: '未上传收据 PDF。',
      visaMissingBookingPdf: '未上传预订 PDF。',
      visaNoGeneratedFile: '没有生成的文件。',
      visaOpenPdfToPrint: '正在打开 PDF 以打印…',
      visaPrintPdfError: '打印 PDF 出错',
      visaPrintDocs: '🖨 打印文件',
      visaFillVisaNumberAndDates: '请填写签证号码和有效期日期。',
      visaGrantedSaved: '签证已批准：信息已保存。',
      visaConfirmGranted: '确认批准',
      visaReadyDocsModalTitle: '可提交文件 -',
      visaProvidedDocsList: '已提供文件列表：',
      visaConfirmReadyToSubmit: '确认可提交',
      visaReadyMarked: '档案已标记为"可提交"。',
      visaRefusedModalTitle: '签证拒绝 - 档案',
      visaRefusedFinalWarning: '此操作不可撤销，档案将被关闭。',
      visaConfirmRefusal: '确认拒绝',
      visaRefusedClosed: '签证被拒：档案已关闭。',
      visaUnauthorized401: '未授权 (401)，请重新登录。',
      visaMissingFileUrl: '缺少文件链接。',
      visaInvalidUrl: '无效链接。',
      visaMissingApiEnv: '缺少 REACT_APP_API_URL (.env)',
      visaLoadingEmployeesError: '加载员工出错',
      visaLoadingFilesError: '加载档案出错',
      visaOpenFileError: '打开档案出错',
      visaUpdateDocError: '更新文件出错',
      visaUpdateFileError: '更新档案出错',
      visaPdfUploading: '正在上传 PDF…',
      visaPdfUploadedSuccess: 'PDF 上传成功。',
      visaUploadError: '上传出错',
      visaGenerating: '正在生成…',
      visaGeneratedSuccess: '文件生成成功。',
      visaGenerationError: '生成出错',
      visaGenerationNotAvailable: '此文件无法生成。',
      visaSendingEmail: '正在发送邮件…',
      visaEmailSent: '邮件已发送 ✅',
      visaEmailNotSent: '邮件未发送 ❌ :',
      visaEmailNotAvailable: '此文件不支持发送邮件。',
      visaEmployeeNotFoundInFile: '档案中找不到员工。',
      visaPdfUploaded: 'PDF 上传成功。',
      visaNoEmployeeFound: '未找到员工',
      
      // Common
      yes: '是',
      no: '否',
      na: '不适用',
      optional: '可选',
      required: '必需',
      success: '成功',
      warning: '警告',
      info: '信息',
      confirm: '确认',
      delete: '删除',
      edit: '编辑',
      view: '查看',
      download: '下载',
      upload: '上传',
      search: '搜索',
      filter: '过滤',
      sort: '排序',
      previous: '上一页',
      next: '下一页',
      first: '首页',
      last: '末页',
      today: '今天',
      yesterday: '昨天',
      thisWeek: '本周',
      thisMonth: '本月',
      thisYear: '今年',
      all: '全部',
      none: '无',
      unknown: '未知',
      notAvailable: '不可用',
      notSpecified: '未指定',
      add: '添加',
      remove: '移除',
      update: '更新',
      create: '创建',
      back: '返回',
      nextStep: '下一步',
      finish: '完成',
      export: '导出',
      import: '导入',
      reset: '重置',
      apply: '应用',
      select: '选择',
      choose: '选择',
      browse: '浏览',
      dragAndDrop: '拖放',
      or: '或',
      and: '和',
      with: '与',
      without: '无',
      per: '每',
      total: '总计',
      average: '平均',
      minimum: '最小',
      maximum: '最大',
      median: '中位数',
      count: '计数',
      percentage: '百分比',
      ratio: '比率',
      date: '日期',
      time: '时间',
      datetime: '日期时间',
      name: '名称',
      fullName: '全名',
      emailAddress: '电子邮件地址',
      phone: '电话',
      address: '地址',
      city: '城市',
      country: '国家',
      postCode: '邮政编码',
      description: '描述',
      comments: '评论',
      notes: '备注',
      remarks: '备注',
      attachment: '附件',
      file: '文件',
      document: '文档',
      image: '图片',
      photo: '照片',
      video: '视频',
      audio: '音频',
      size: '大小',
      format: '格式',
      extension: '扩展名',
      dimensions: '尺寸',
      resolution: '分辨率',
      quality: '质量',
      preferences: '偏好',
      configuration: '配置',
      options: '选项',
      advanced: '高级',
      basic: '基础',
      simple: '简单',
      complex: '复杂',
      easy: '容易',
      difficult: '困难',
      quick: '快速',
      slow: '缓慢',
      fast: '快速',
      new: '新',
      old: '旧',
      recent: '最近',
      current: '当前',
      future: '未来',
      past: '过去',
      present: '现在',
      active: '活跃',
      inactive: '不活跃',
      enabled: '启用',
      disabled: '禁用',
      visible: '可见',
      hidden: '隐藏',
      public: '公开',
      private: '私有',
      shared: '共享',
      personal: '个人',
      professional: '专业',
      business: '商业',
      financialInfo: '财务信息',
      legalInfo: '法律信息',
      employee_ID: '员工ID',
      noEmployeesRegistered: '无注册员工',
      startByAddingFirstEmployee: '从添加第一名员工开始',
      exportSuccess: '导出成功',
      exportError: '导出错误',
      errorLoadingDashboard: '加载仪表板错误',
      loadingStats: '加载统计中...',
      errorLoadingEmployees: '加载员工错误',
      errorLoadingEmployeesAlert: '加载员工列表错误',
      loadingEmployees: '加载员工中...',
    }
  };

  const t = (key, params = {}) => {
    let translation = translations[language]?.[key] || key;
    
    // Remplacer les paramètres dans la traduction
    Object.keys(params).forEach(param => {
      translation = translation.replace(`{{${param}}}`, params[param]);
    });
    
    return translation;
  };

  const getAvailableLanguages = () => {
    return [
      { code: 'fr', name: 'Français', flag: '🇫🇷' },
      { code: 'en', name: 'English', flag: '🇬🇧' },
      { code: 'zh', name: '中文', flag: '🇨🇳' }
    ];
  };

  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage, 
      t,
      getAvailableLanguages
    }}>
      {children}
    </LanguageContext.Provider>
  );
};
